# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('company_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrandTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'brand_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyBoxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('marketplace', models.CharField(max_length=250)),
                ('url', models.TextField(blank=True, null=True)),
                ('is_out_of_stock', models.BooleanField()),
                ('no_longer_available', models.NullBooleanField()),
                ('first_party_owned', models.NullBooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupsSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'groups_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutOfStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('is_out_of_stock', models.BooleanField()),
                ('no_longer_available', models.NullBooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('crawl', models.NullBooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.NullBooleanField()),
                ('with_price', models.NullBooleanField()),
                ('urgent', models.NullBooleanField()),
                ('is_custom_filter', models.NullBooleanField()),
                ('crawl_frequency', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
                ('ignore_variant_data', models.BooleanField()),
            ],
            options={
                'db_table': 'product_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductListResultsSummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_list_results_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField(blank=True, null=True)),
                ('site_id', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingSearchResultsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('date_of_upload', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ranking_search_results_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingSearchResultsItemsSummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField()),
                ('total_results', models.IntegerField(blank=True, null=True)),
                ('brand_results', models.IntegerField(blank=True, null=True)),
                ('search_items_brands_relation_id', models.IntegerField()),
                ('date_of_upload', models.DateField(blank=True, null=True)),
                ('on_first_page', models.TextField()),
            ],
            options={
                'db_table': 'ranking_search_results_items_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('total_count', models.IntegerField()),
                ('average_num', models.FloatField()),
                ('one_star', models.IntegerField()),
                ('two_star', models.IntegerField()),
                ('three_star', models.IntegerField()),
                ('four_star', models.IntegerField()),
                ('five_star', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('group_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'search_terms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTermsBrandsRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_id', models.IntegerField()),
            ],
            options={
                'db_table': 'search_terms_brands_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTermsGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.NullBooleanField()),
            ],
            options={
                'db_table': 'search_terms_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=255)),
                ('image_url', models.TextField()),
                ('site_type', models.IntegerField()),
                ('results_per_page', models.IntegerField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('traffic_upload', models.NullBooleanField()),
                ('crawler_name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_address', models.CharField(max_length=32)),
                ('request_method', models.CharField(max_length=20)),
                ('request_path', models.CharField(max_length=400)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('run_time', models.FloatField()),
            ],
            options={
                'db_table': 'api_insights_log',
            },
        ),
    ]
