Vagrant.configure("2") do |config|
    # If you are behind a corporate proxy, install the plugin and set:
    # config.proxy.http = 'http://example.com:3128/'
    # config.proxy.https = 'http://example.com:3128/'

    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64"
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "keywords.dev"

    config.vm.network :private_network, ip: "33.33.33.58"
    config.vm.network :forwarded_port, host: 6543, guest: 6543

    config.ssh.forward_agent = true
end

