{"url": "http://www1.bloomingdales.com/search/index.ognc?designer=Women&Action=designer", "text": "Designers", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=2910&PageID=12498698395314", "text": "Women", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=2911&PageID=12505560750024", "text": "Contemporary", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=16961&PageID=72847022540303", "text": "Shoes", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=16958&PageID=72835588252816", "text": "Handbags", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=3376&PageID=14502903908192", "text": "Jewelry and Accessories", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=3864&PageID=16595938932650", "text": "Men", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=3866&PageID=16607087494679", "text": "Kids", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=2921&PageID=12547818849186", "text": "Beauty", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=3865&PageID=16603050684416", "text": "Home", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=3977&PageID=17081952667231", "text": "Sale", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=2917&PageID=40064318413667", "text": "Plus Sizes", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=16975&PageID=51176308713129", "text": "Fine Jewelry and Watches", "level": 1}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=3948&PageID=16957179591995", "text": "Gifts and Gift Cards", "level": 1}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/new-arrivals?id=1001038", "text": "New Arrivals", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/latest-looks?id=1001040", "text": "Latest Looks", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/theory?id=8991", "text": "Theory Lookbook", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/tibi?id=1001621", "text": "Tibi Lookbook", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/free-people-2013.jsp", "text": "Free People Lookbook", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/new-arrivals?id=1001037", "text": "New Arrivals", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/theory-classics?id=20295", "text": "Theory Classics", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/dress-code-2013.jsp", "text": "The Dress Code", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://bloomingdalesfashionpacked.com/index.aspx", "text": "Fashion-Packed Guide: August", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fashion-lookbooks-videos-style-guide?id=13668", "text": "All Trends & Lookbooks", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/latest-looks?id=1001039", "text": "Latest Looks", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/theory?id=10201", "text": "Theory Lookbook", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/tibi?id=1001621", "text": "Tibi Lookbook", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/free-people-2013.jsp", "text": "Free People Lookbook", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/premium-designers?id=1000674", "text": "Premium Designers", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/best-sellers?id=23268", "text": "Best Sellers", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=15915", "text": "Contemporary Plus", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/quotation-boutique?id=22193", "text": "Quotation Boutique", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/premium-designers?id=1001622", "text": "Premium Designers", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/blazers-jackets?id=1001523", "text": "Blazers & Jackets", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/cashmere-shop?id=1000654", "text": "Cashmere Shop", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/theory-classics?id=20294", "text": "Theory Classics", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/dress-code-2013.jsp", "text": "The Dress Code", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/kate-spade-new-york-fall-2013.jsp", "text": "kate spade new york Lookbook", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://bloomingdalesfashionpacked.com/index.aspx", "text": "Fashion-Packed Guide: August", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fashion-lookbooks-videos-style-guide?id=13668", "text": "All Trends & Lookbooks", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/sandals-under-100?id=17526", "text": "Sandals Under $100", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/new-arrivals?id=19852", "text": "New Arrivals", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/new-designers?id=1001251", "text": "New Designers", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/premium-shoes-handbags-fall-2013.jsp", "text": "Premium Designer Lookbook", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/ultimate-accessories-wardrobe-spring-2013.jsp", "text": "Ultimate Accessories Wardrobe", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/new-arrivals?id=20592", "text": "New Arrivals", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/premium-designers?id=1000341", "text": "Premium Designers", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=16975&cm_sp=FineJewerly-_-Leftnav-_-JABoutiques", "text": "Fine Jewelry & Watches", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/coats?id=1001522", "text": "Coats", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/denim?id=8573", "text": "Denim", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/dresses?id=8608", "text": "Dresses", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/lingerie-bras-shapewear?id=17613", "text": "Lingerie, Bras & Shapewear", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/lounge-active?id=8613", "text": "Lounge & Active", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=2911", "text": "Contemporary", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=2917", "text": "Plus Sizes", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/petites?id=17378", "text": "Petites", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/catalog/index.ognc?CategoryID=1001622", "text": "Premium Designers", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/blazers-jackets?id=1001521", "text": "Blazers & Jackets", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/kate-spade-new-york-fall-2013.jsp", "text": "kate spade new york Lookbook", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fashion-lookbooks-videos-style-guide?id=13668", "text": "All Trends & Lookbooks", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/boots?id=19212", "text": "Boots", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/booties?id=1000692", "text": "Booties", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/flats?id=16963", "text": "Flats", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/latest-looks?id=1001080", "text": "Latest Looks", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/the-suit-shop?id=1000177", "text": "The Suit Shop", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/coats-jackets?id=11548", "text": "Coats & Jackets", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/denim?id=10172", "text": "Denim", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/dress-shirts?id=17647", "text": "Dress Shirts", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/handbags-under-300?id=22559", "text": "Handbags Under $300", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/best-sellers?id=23173", "text": "Best Sellers", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/new-arrivals?id=22173", "text": "New Arrivals", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/premium-shoes-handbags-fall-2013.jsp", "text": "Premium Designer Lookbook", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/ultimate-accessories-wardrobe-spring-2013.jsp", "text": "Ultimate Accessories Wardrobe", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/kate-spade-new-york-fall-2013.jsp", "text": " kate spade new york Lookbook", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/campaign/social?campaign_id=319&channel_id=1", "text": "PANDORA: Build Your Own Bracelet", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/memorable-gifts?id=1001575", "text": "Memorable Gifts", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/special-occasion-jewelry?id=1001577", "text": "Special Occasion Jewelry", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/watches-under-200?id=1001578", "text": "Watches Under $200", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/ultimate-accessories-wardrobe-spring-2013.jsp", "text": "Ultimate Accessories Wardrobe", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/newborn-0-9-months?id=23708", "text": "Newborn (0-9 months)", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/pants-leggings?id=5451", "text": "Pants & Leggings", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/skirts-shorts?id=1000660", "text": "Skirts & Shorts", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/sleepwear-robes?id=21434", "text": "Sleepwear & Robes", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/sweaters?id=12629", "text": "Sweaters", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/swimsuits-coverups?id=8722", "text": "Swimsuits & Coverups", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/cashmere-shop?id=1000658", "text": "Cashmere Shop", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/coats?id=1001520", "text": "Coats", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/denim?id=5545", "text": "Denim", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/dresses?id=21683", "text": "Dresses", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/party-evening?id=17396", "text": "Party & Evening", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/pumps?id=17397", "text": "Pumps", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/sandals?id=17398", "text": "Sandals", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/sneakers?id=17400", "text": "Sneakers", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/wedges-espadrilles?id=17402", "text": "Wedges & Espadrilles", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/pants?id=10189", "text": "Pants", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/polos?id=1000663", "text": "Polos", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/shorts-swim?id=11576", "text": "Shorts & Swim", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/sport-shirts?id=17648", "text": "Sport Shirts", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/suits-sport-coats?id=1000074", "text": "Suits & Sport Coats", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/sweaters?id=10258", "text": "Sweaters", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fashion-lookbooks-videos-style-guide?id=13668", "text": "All Trends & Lookbooks", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/marc-by-marc-jacobs?id=23558", "text": "MARC BY MARC JACOBS", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/marc-jacobs?id=23563", "text": "Marc Jacobs", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/mcm?id=1000340", "text": "MCM", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/michael-michael-kors?id=23561", "text": "MICHAEL Michael Kors", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/fashion-index/kate-spade-new-york-fall-2013.jsp", "text": "kate spade new york Lookbook", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fashion-lookbooks-videos-style-guide?id=13668", "text": "All Trends & Lookbooks", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/all-watches?id=20532", "text": "All Watches", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/bracelets?id=8701", "text": "Bracelets", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/earrings?id=3628", "text": "Earrings", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/infant-girl-0-24-months?id=23712", "text": "Infant Girl (0-24 months)", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/infant-boy-0-24-months?id=23713", "text": "Infant Boy (0-24 months)", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/bath-diapering?id=1001242", "text": "Bath & Diapering", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/bedding-decor?id=1001243", "text": "Bedding & Decor", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/feeding?id=1000107", "text": "Feeding", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/bath?id=1000242", "text": "Bath", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/women?id=3985", "text": "Women", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/contemporary?id=19718", "text": "Contemporary", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/tights-socks-hosiery?id=22316", "text": "Tights, Socks & Hosiery", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/tops-tees?id=10026", "text": "Tops & Tees", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/wear-to-work?id=2941", "text": "Wear to Work", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/alice-olivia?id=22114", "text": "Alice + Olivia", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/aqua?id=8961", "text": "Aqua", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/lingerie-bras-shapewear?id=5566", "text": "Lingerie, Bras & Shapewear", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/lounge-active?id=11817", "text": "Lounge & Active", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/pants-leggings?id=17566", "text": "Pants & Leggings", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/skirts-shorts?id=1000662", "text": "Skirts & Shorts", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/sleepwear-robes?id=21429", "text": "Sleepwear & Robes", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/all-shoes?id=17411", "text": "All Shoes", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/coach/catalog/index.ognc?CategoryID=21535", "text": "COACH", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/dolce-vita-dv-dolce-vita?id=1000614", "text": "Dolce Vita/DV Dolce Vita", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/frye?id=1000616", "text": "Frye", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/michael-michael-kors?id=1000610", "text": "MICHAEL Michael Kors", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/tees-sweatshirts?id=11536", "text": "Tees & Sweatshirts", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/ties?id=10236", "text": "Ties", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/underwear-loungewear-socks?id=10237", "text": "Underwear, Loungewear & Socks", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/boots?id=1000046", "text": "Boots", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/dress-shoes?id=1001183", "text": "Dress Shoes", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/rebecca-minkoff?id=23564", "text": "Rebecca Minkoff", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/tory-burch?id=23557", "text": "Tory Burch", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/salvatore-ferragamo?id=1001484", "text": "Salvatore Ferragamo", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/all-designers/handbags?id=1001340", "text": "All Designers", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/clutches?id=17309", "text": "Clutches", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/necklaces?id=3629", "text": "Necklaces", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/rings?id=3630", "text": "Rings", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/charms?id=1000342", "text": "Charms", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/all-jewelry?id=20033", "text": "All Jewelry", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/aviator?id=4522", "text": "Aviator", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/gifts?id=23715", "text": "Gifts", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/toys?id=1000307", "text": "Toys", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/travel-gear?id=1001244", "text": "Travel Gear", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/girls-2-6x?id=23719", "text": "Girls 2-6X", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/girls-7-16?id=23720", "text": "Girls 7-16", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/bedding?id=1000243", "text": "Bedding", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/dinnerware?id=1000231", "text": "Dinnerware", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/flatware?id=1000233", "text": "Flatware", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/glassware-barware?id=1000232", "text": "Glassware & Barware", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/serveware?id=1000234", "text": "Serveware", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/shoes?id=4841", "text": "Shoes", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/handbags?id=5070", "text": "Handbags", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/jewelry-accessories?id=5303", "text": "Jewelry & Accessories", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/fine-jewelry?id=1001014", "text": "Fine Jewelry", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/men?id=1001174", "text": "Men", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/kids?id=5320", "text": "Kids", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/exclusives?id=1001276", "text": "Exclusives", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/new-arrivals?id=3697", "text": "New Arrivals", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/diane-von-furstenberg?id=8912", "text": "DIANE von FURSTENBERG", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/free-people?id=12938", "text": "Free People", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/helmut-lang?id=1001195", "text": "Helmut Lang", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/sweaters?id=12374", "text": "Sweaters", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/swimsuits-coverups?id=5609", "text": "Swimsuits & Coverups", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/tights-socks-hosiery?id=22314", "text": "Tights, Socks & Hosiery", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/tops-tees?id=5619", "text": "Tops & Tees", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/salvatore-ferragamo?id=1001481", "text": "Salvatore Ferragamo", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/sam-edelman?id=1000613", "text": "Sam Edelman", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/stuart-weitzman?id=1000608", "text": "Stuart Weitzman", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/shoes/tory-burch?id=1000607", "text": "Tory Burch", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/all-designers/shoes?id=1001339", "text": "All Designers", "level": 2, "parent_text": "Shoes", "parent_url": "http://www1.bloomingdales.com/shop/shoes?id=16961&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/loafers-drivers?id=1000050", "text": "Loafers & Drivers", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/oxfords?id=1001314", "text": "Oxfords", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/sandals?id=1000051", "text": "Sandals", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/sneakers?id=1000054", "text": "Sneakers", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/crossbody-mini-bags?id=17310", "text": "Crossbody & Mini Bags", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/hobos?id=17311", "text": "Hobos", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/satchels?id=17312", "text": "Satchels", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/shoulder-bags?id=17314", "text": "Shoulder Bags", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/cat-eye?id=20024", "text": "Cat Eye", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/oversized?id=21104", "text": "Oversized", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/boys-2-7?id=23722", "text": "Boys 2-7", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/boys-8-20?id=23723", "text": "Boys 8-20", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/accessories?id=1001235", "text": "Accessories", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/bedding?id=1001312", "text": "Bedding", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/table-linens?id=1000246", "text": "Table Linens", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/bakeware?id=1000235", "text": "Bakeware", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/coffee-espresso-tea?id=1000236", "text": "Coffee, Espresso & Tea", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/cookware?id=1000237", "text": "Cookware", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/home?id=6466", "text": "Home", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/plus-sizes?id=5220", "text": "Plus Sizes", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/sale/petites?id=19968", "text": "Petites", "level": 2, "parent_text": "Sale", "parent_url": "http://www1.bloomingdales.com/shop/sale?id=3977&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/under-500?id=1001277", "text": "Under $500", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/earrings?id=20548", "text": "Earrings", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/bracelets?id=17804", "text": "Bracelets", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/contemporary-designers?id=15915", "text": "Contemporary Designers", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/cashmere-shop?id=17013", "text": "Cashmere Shop ", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/coats-jackets-blazers?id=5471", "text": "Coats, Jackets & Blazers", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/denim?id=5466", "text": "Denim", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/dresses?id=5467", "text": "Dresses", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/joie?id=21913", "text": "Joie", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/marc-by-marc-jacobs?id=8990", "text": "MARC BY MARC JACOBS", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/splendid?id=23667", "text": "Splendid", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/theory?id=8991", "text": "Theory", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/wear-to-work?id=10527", "text": "Wear to Work", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/aqua?id=10194", "text": "Aqua", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/diane-von-furstenberg?id=10197", "text": "DIANE von FURSTENBERG", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/eileen-fisher?id=10205", "text": "Eileen Fisher", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/joie?id=23671", "text": "Joie", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/all-shoes?id=1000055", "text": "All Shoes", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/bags-briefcases?id=1000059", "text": "Bags & Briefcases", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/belts?id=1000060", "text": "Belts", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/cufflinks-jewelry?id=1000061", "text": "Cufflinks & Jewelry", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/totes?id=19993", "text": "Totes", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/travel-baby-bags?id=1000369", "text": "Travel & Baby Bags", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/all-handbags?id=17316", "text": "All Handbags", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/cosmetic-bags?id=1000415", "text": "Cosmetic Bags", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/polarized?id=1001443", "text": "Polarized", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/shield?id=20025", "text": "Shield", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/wayfarer?id=1000091", "text": "Wayfarer", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/all-sunglasses?id=4520", "text": "All Sunglasses", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/belts?id=3631", "text": "Belts", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/shoes?id=1001238", "text": "Shoes", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/toys?id=1001236", "text": "Toys", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/kids/aqua?id=23732", "text": "Aqua", "level": 2, "parent_text": "Kids", "parent_url": "http://www1.bloomingdales.com/shop/kids?id=3866&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/cutlery?id=1000238", "text": "Cutlery", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/gadgets-tools?id=1000240", "text": "Gadgets & Tools", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/books?id=1001540", "text": "Books", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/bowls-trays?id=1001541", "text": "Bowls & Trays", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/candles-home-fragrances?id=1001542", "text": "Candles & Home Fragrances", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/necklaces?id=17805", "text": "Necklaces", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/rings?id=17806", "text": "Rings", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/fine-watches?id=22108", "text": "Fine Watches", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/bloomingdales-collection/diamonds?id=20949", "text": "Diamonds", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/intimates-sleepwear?id=3704", "text": "Intimates & Sleepwear", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/pants-skirts-shorts?id=16308", "text": "Pants, Skirts & Shorts", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/sweaters?id=16184", "text": "Sweaters", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/tops-tees?id=5503", "text": "Tops & Tees", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/tibi?id=1001621", "text": "Tibi", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/contemporary-apparel/vince?id=13574", "text": "Vince", "level": 2, "parent_text": "Contemporary", "parent_url": "http://www1.bloomingdales.com/shop/contemporary-apparel?id=2911&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/theory?id=10201", "text": "Theory", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/womens-apparel/vince?id=1000299", "text": "Vince", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/all-designers/womens-apparel?id=1001337", "text": "All Designers", "level": 2, "parent_text": "Women", "parent_url": "http://www1.bloomingdales.com/shop/womens-apparel?id=2910&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/hats-gloves-scarves?id=1000062", "text": "Hats, Gloves & Scarves", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/sunglasses?id=1000068", "text": "Sunglasses", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/tech-accessories-cases?id=1000833", "text": "Tech Accessories & Cases", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/tech-accessories-cases?id=1000416", "text": "Tech Accessories & Cases", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/wallets-wristlets?id=1000417", "text": "Wallets & Wristlets", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/handbags/all-small-accessories?id=1000431", "text": "All Small Accessories", "level": 2, "parent_text": "Handbags", "parent_url": "http://www1.bloomingdales.com/shop/handbags?id=16958&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/scarves-hats-gloves?id=21311", "text": "Scarves, Hats & Gloves", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/tech-accessories-cases?id=21485", "text": "Tech Accessories & Cases", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/tights-socks-hosiery?id=3637", "text": "Tights, Socks & Hosiery", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/all-accessories?id=20034", "text": "All Accessories", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/collectibles?id=1001543", "text": "Collectibles", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/desk-accessories?id=1001544", "text": "Desk Accessories", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/holiday-decor?id=1001545", "text": "Holiday D\u00e9cor", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/mirrors-wall-art?id=1001546", "text": "Mirrors & Wall Art", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/mens?id=1001010", "text": "Men's", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/all-jewelry-watches?id=1000931", "text": "All Jewelry & Watches", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/charriol?id=17789", "text": "Charriol", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/ippolita?id=20543", "text": "IPPOLITA", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/john-hardy?id=20695", "text": "John Hardy", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/all-plus-sizes?id=1000444", "text": "All Plus Sizes", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/eileen-fisher?id=9029", "text": "Eileen Fisher", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/lafayette-148-new-york?id=19204", "text": "Lafayette 148 New York", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/michael-michael-kors?id=20311", "text": "MICHAEL Michael Kors", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/wallets?id=1000065", "text": "Wallets", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/watches?id=1000066", "text": "Watches", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/all-accessories?id=1000070", "text": "All Accessories", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/the-lab-contemporary-designers?id=1000425", "text": "The Lab: Contemporary Designers", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/alexis-bittar?id=1001031", "text": "Alexis Bittar", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/marc-by-marc-jacobs?id=21257", "text": "MARC BY MARC JACOBS", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/michael-kors?id=21253", "text": "Michael Kors", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/michele?id=16296", "text": "MICHELE", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/picture-frames?id=1001547", "text": "Picture Frames", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/pillows-throws?id=1001548", "text": "Pillows & Throws", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/vases?id=1001549", "text": "Vases", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/kids-bedding?id=1000433", "text": "Kids' Bedding", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/lighting?id=1001009", "text": "Lighting", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/judith-ripka?id=20842", "text": "Judith Ripka", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/lagos?id=20824", "text": "Lagos", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/movado-bold?id=23693", "text": "Movado BOLD", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/pandora?id=1000247 ", "text": "PANDORA", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/plus-size-apparel/vince-camuto?id=9027", "text": "VINCE CAMUTO", "level": 2, "parent_text": "Plus Sizes", "parent_url": "http://www1.bloomingdales.com/shop/plus-size-apparel?id=2917&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/john-varvatos?id=1000373", "text": "John Varvatos", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/salvatore-ferragamo?id=1001483", "text": "Salvatore Ferragamo", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/theory?id=19524", "text": "Theory", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/mens/vince?id=1000419", "text": "Vince", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/all-designers/mens-apparel?id=1001338", "text": "All Designers", "level": 2, "parent_text": "Men", "parent_url": "http://www1.bloomingdales.com/shop/mens?id=3864&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/ray-ban?id=9314", "text": "Ray-Ban", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/salvatore-ferragamo?id=1001324", "text": "Salvatore Ferragamo", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/jewelry-accessories/tom-ford?id=22318", "text": "Tom Ford", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/all-designers/jewelry-accessories?id=1001342", "text": "All Designers", "level": 2, "parent_text": "Jewelry and Accessories", "parent_url": "http://www1.bloomingdales.com/shop/jewelry-accessories?id=3376&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/luggage?id=1000257", "text": "Luggage", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/outdoor-entertaining?id=1000354", "text": "Outdoor Entertaining", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/pet?id=1000434", "text": "Pet", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/rugs?id=1001397", "text": "Rugs", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/gifts?id=1001550", "text": "Gifts", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/all-designers?id=23694", "text": "All Designers", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/colored-gemstones?id=21107", "text": "Colored Gemstones", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/diamonds?id=20949", "text": "Diamonds", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/gold?id=17799", "text": "Gold", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/cutlery?id=1000238", "text": "The Cutting Edge", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/glassware-barware?id=1000232", "text": "Barware Essentials", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/bedding?id=1000243", "text": "The Bedding Refresh", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/all-guides?id=1001556", "text": "All Guides", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/cuisinart?id=20026", "text": "Cuisinart", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/fine-jewelry/pearls?id=22089", "text": "Pearls", "level": 2, "parent_text": "Fine Jewelry and Watches", "parent_url": "http://www1.bloomingdales.com/shop/fine-jewelry?id=16975&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/hudson-park?id=19130", "text": "Hudson Park", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/michael-aram?id=1001477", "text": "Michael Aram", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
{"url": "http://www1.bloomingdales.com/shop/home/villeroy-boch?id=16328", "text": "Villeroy & Boch", "level": 2, "parent_text": "Home", "parent_url": "http://www1.bloomingdales.com/shop/home?id=3865&intnl=true"}
