{"Group_members": [{"text": "Sports & Outdoors", "site": "amazon", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Health-Fitness/pcmcat242800050021.c?id=pcmcat242800050021", "text": "Health, Fitness & Sports", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.bjs.com/sports.category.986.2000149", "text": "Sports", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Sports-Toys/5/store.html", "text": "Sports & Toys", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/sports-outdoors/4125?povid=cat121828-env999999-moduleA072012-lLinkGNAV5_SportsFitnessOutdoors", "text": "Sports, Fitness & Outdoors", "site": "walmart", "level": 1}, {"url": "http://www.wayfair.com/Outdoor-C32334.html", "text": "Outdoor", "site": "wayfair", "level": 1}], "Level": 1, "Short_name": "Sports, Fitness, Outdoors", "Group_name": "Outdoor; Health, Fitness & Sports; Sports, Fitness & Outdoors; Sports; Sports & Toys; Sports & Outdoors"}

{"Group_members": [{"text": "Sports & Outdoors", "site": "amazon", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Health-Fitness/pcmcat242800050021.c?id=pcmcat242800050021", "text": "Health, Fitness & Sports", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.bjs.com/sports.category.986.2000149", "text": "Sports", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Sports-Toys/5/store.html", "text": "Sports & Toys", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/sports-outdoors/4125?povid=cat121828-env999999-moduleA072012-lLinkGNAV5_SportsFitnessOutdoors", "text": "Sports, Fitness & Outdoors", "site": "walmart", "level": 1}, {"text": "Grocery, Health & Beauty", "site": "amazon", "level": 1}, {"url": "http://www.bjs.com/health--beauty.category.850.2001045", "text": "Health & Beauty", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Health-Beauty/8/store.html", "text": "Health & Beauty", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/976760?povid=cat121828-env999999-moduleA072012-lLinkGNAV3_Health", "text": "Health", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Sports, Health, Fitness", "Group_name": "Health, Fitness & Sports; Grocery, Health & Beauty; Sports, Fitness & Outdoors; Health & Beauty; Sports; Health; Sports & Toys; Sports & Outdoors"}

{"Group_members": [{"text": "Grocery, Health & Beauty", "site": "amazon", "level": 1}, {"url": "http://www.walmart.com/cp/Grocery/976759?povid=cat121828-env999999-moduleA072012-lLinkGNAV2_Grocery", "text": "Grocery", "site": "walmart", "level": 1}, {"url": "http://grocery.walmart.com/?povid=cat121828-env999999-moduleA072012-lLinkGNAV2_GroceryDeliveryBeta", "text": "Grocery Delivery", "site": "walmart", "level": 1}, {"url": "http://www.bjs.com/health--beauty.category.850.2001045", "text": "Health & Beauty", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Health-Beauty/8/store.html", "text": "Health & Beauty", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/1085666?povid=cat121828-env999999-moduleA072012-lLinkGNAV1_Beauty_Beauty", "text": "Beauty", "site": "walmart", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Health-Fitness/pcmcat242800050021.c?id=pcmcat242800050021", "text": "Health, Fitness & Sports", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.walmart.com/cp/976760?povid=cat121828-env999999-moduleA072012-lLinkGNAV3_Health", "text": "Health", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Grocery, Beauty, Health", "Group_name": "Grocery; Health, Fitness & Sports; Beauty; Grocery, Health & Beauty; Health & Beauty; Health; Grocery Delivery"}

{"Group_members": [{"text": "Toys, Kids & Baby", "site": "amazon", "level": 1}, {"url": "http://www.bjs.com/baby.category.1035.2002451", "text": "Baby", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Baby/35/store.html", "text": "Baby", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/Baby/5427?povid=cat121828-env999999-moduleA072012-lLinkGNAV1_Baby_Baby", "text": "Baby", "site": "walmart", "level": 1}, {"url": "http://www.wayfair.com/Baby-and-Kids-C45226.html", "text": "Baby & Kids", "site": "wayfair", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Home/Toys-Games/pcmcat252700050006.c?id=pcmcat252700050006", "text": "Toys & Games", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.bjs.com/toys.category.808.2000705", "text": "Toys", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Sports-Toys/5/store.html", "text": "Sports & Toys", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/Toys/4171?povid=cat121828-env999999-moduleA072012-lLinkGNAV5_Toys", "text": "Toys", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Baby, Kids, Toys", "Group_name": "Toys & Games; Toys; Toys, Kids & Baby; Baby & Kids; Sports & Toys; Baby"}

{"Group_members": [{"text": "Movies, Music & Games", "site": "amazon", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Music-Movies/abcat0600000.c?id=abcat0600000", "text": "Movies & Music", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.walmart.com/cp/movies-tv/4096?povid=cat121828-env999999-moduleA072012-lLinkGNAV4_Movies", "text": "Movies", "site": "walmart", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Audio/Musical-Instruments/abcat0207000.c?id=abcat0207000", "text": "Musical Instruments", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.walmart.com/cp/Music/4104?povid=cat121828-env999999-moduleA072012-lLinkGNAV4_Music", "text": "Music", "site": "walmart", "level": 1}, {"text": "Digital Games & Software", "site": "amazon", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Video-Games/abcat0700000.c?id=abcat0700000", "text": "Video Games", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"level": 1, "url": "http://www.bestbuy.com/site/Home/Toys-Games/pcmcat252700050006.c?id=pcmcat252700050006", "text": "Toys & Games", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.walmart.com/cp/1091906?povid=cat121828-env999999-moduleA072012-lLinkGNAV1_Campaign_GameTime", "text": "Game Time", "site": "walmart", "level": 1}, {"url": "http://www.walmart.com/cp/Video-Games/2636?povid=cat121828-env999999-moduleA072012-lLinkGNAV5_VideoGames", "text": "Video Games", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Movies, Music, Games, Instruments, Video", "Group_name": "Movies & Music; Toys & Games; Digital Games & Software; Video Games; Movies; Movies, Music & Games; Musical Instruments; Music; Game Time"}

{"Group_members": [{"text": "Digital Games & Software", "site": "amazon", "level": 1}, {"text": "Movies, Music & Games", "site": "amazon", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Video-Games/abcat0700000.c?id=abcat0700000", "text": "Video Games", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"level": 1, "url": "http://www.bestbuy.com/site/Home/Toys-Games/pcmcat252700050006.c?id=pcmcat252700050006", "text": "Toys & Games", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.walmart.com/cp/1091906?povid=cat121828-env999999-moduleA072012-lLinkGNAV1_Campaign_GameTime", "text": "Game Time", "site": "walmart", "level": 1}, {"url": "http://www.walmart.com/cp/Video-Games/2636?povid=cat121828-env999999-moduleA072012-lLinkGNAV5_VideoGames", "text": "Video Games", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Software, Digital, Games", "Group_name": "Toys & Games; Digital Games & Software; Video Games; Game Time; Movies, Music & Games"}

{"Group_members": [{"url": "http://www.overstock.com/Worldstock-Fair-Trade/6/store.html", "text": "Worldstock Fair Trade", "site": "overstock", "level": 1}], "Level": 1, "Short_name": "Worldstock, Fair, Trade", "Group_name": "Worldstock Fair Trade"}

{"Group_members": [{"text": "MP3s & Cloud Player", "site": "amazon", "level": 1}, {"text": "Amazon Cloud Drive", "site": "amazon", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Audio/abcat0200000.c?id=abcat0200000", "text": "Audio & MP3", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}], "Level": 1, "Short_name": "Player, Cloud, MP3s, Audio", "Group_name": "MP3s & Cloud Player; Amazon Cloud Drive; Audio & MP3"}

{"Group_members": [{"text": "Amazon Cloud Drive", "site": "amazon", "level": 1}, {"text": "MP3s & Cloud Player", "site": "amazon", "level": 1}], "Level": 1, "Short_name": "Amazon, Drive, Cloud", "Group_name": "MP3s & Cloud Player; Amazon Cloud Drive"}

{"Group_members": [{"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Car-Audio-GPS/abcat0300000.c?id=abcat0300000", "text": "Car, Marine & GPS", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}], "Level": 1, "Short_name": "Marine, Car, GPS", "Group_name": "Car, Marine & GPS"}

{"Group_members": [{"url": "http://www.overstock.com/Main-Street-Revolution/39/store.html", "text": "Main Street Revolution", "site": "overstock", "level": 1}], "Level": 1, "Short_name": "Revolution, Street, Main", "Group_name": "Main Street Revolution"}

{"Group_members": [{"text": "Home, Garden & Tools", "site": "amazon", "level": 1}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/TV-Video/abcat0100000.c?id=abcat0100000", "text": "TV & Home Theater", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Home/pcmcat248700050021.c?id=pcmcat248700050021", "text": "Home", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}, {"url": "http://www.bjs.com/home.category.385.2000199", "text": "Home", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Home-Garden/1/store.html", "text": "Home & Garden", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/For-the-Home/4044?povid=cat121828-env999999-moduleA072012-lLinkGNAV3_Home", "text": "Home", "site": "walmart", "level": 1}, {"url": "http://www.walmart.com/cp/Home-Improvement/1072864?povid=cat121828-env999999-moduleA072012-lLinkGNAV3_HomeImprovement_HomeImprovement", "text": "Home Improvement", "site": "walmart", "level": 1}, {"url": "http://www.wayfair.com/Home-Improvement-C45342.html", "text": "Home Improvement", "site": "wayfair", "level": 1}, {"url": "http://www.walmart.com/cp/patio-garden/5428?povid=cat121828-env999999-moduleA072012-lLinkGNAV4_PatioGarden", "text": "Patio & Garden", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Home, Tools, Garden, Improvement", "Group_name": "TV & Home Theater; Home Improvement; Home & Garden; Patio & Garden; Home; Home, Garden & Tools"}

{"Group_members": [{"text": "Clothing, Shoes & Jewelry", "site": "amazon", "level": 1}, {"url": "http://www.overstock.com/Clothing-Shoes/7/store.html", "text": "Clothing & Shoes", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/Apparel/5438?povid=cat121828-env999999-moduleA072012-lLinkGNAV1_Apparel_ApparelShoesAccessories", "text": "Apparel, Shoes & Accessories", "site": "walmart", "level": 1}, {"url": "http://www.bjs.com/jewelry.category.100.2000297", "text": "Jewelry", "site": "bjs", "level": 1}, {"url": "http://www.overstock.com/Jewelry-Watches/4/store.html", "text": "Jewelry & Watches", "site": "overstock", "level": 1}, {"url": "http://www.walmart.com/cp/Jewelry/3891?povid=cat121828-env999999-moduleA072012-lLinkGNAV3_Jewelry", "text": "Jewelry", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Clothing, Shoes, Jewelry, Watches", "Group_name": "Jewelry; Jewelry & Watches; Clothing, Shoes & Jewelry; Clothing & Shoes; Apparel, Shoes & Accessories"}

{"Group_members": [{"url": "http://www.walmart.com/cp/Apparel/5438?povid=cat121828-env999999-moduleA072012-lLinkGNAV1_Apparel_ApparelShoesAccessories", "text": "Apparel, Shoes & Accessories", "site": "walmart", "level": 1}, {"text": "Clothing, Shoes & Jewelry", "site": "amazon", "level": 1}, {"url": "http://www.overstock.com/Clothing-Shoes/7/store.html", "text": "Clothing & Shoes", "site": "overstock", "level": 1}], "Level": 1, "Short_name": "Apparel, Accessories, Shoes", "Group_name": "Apparel, Shoes & Accessories; Clothing & Shoes; Clothing, Shoes & Jewelry"}

{"Group_members": [{"url": "http://www.walmart.com/cp/1094926?povid=cat121828-env999999-moduleA030713-lLinkGNAV1_Campaign_EmpoweringWomenTogether", "text": "Empowering Women Together", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Together, Women, Empowering", "Group_name": "Empowering Women Together"}

{"Group_members": [{"url": "http://www.overstock.com/Wounded-Warrior-Project/41/store.html", "text": "Wounded Warrior Project", "site": "overstock", "level": 1}], "Level": 1, "Short_name": "Project, Wounded, Warrior", "Group_name": "Wounded Warrior Project"}

{"Group_members": [{"url": "http://www.walmart.com/cp/1099404?povid=cat121828-env999999-moduleA112212-lLinkGNAV1_Campaign_SuperHerosSuperStore", "text": "Super Heroes Store", "site": "walmart", "level": 1}], "Level": 1, "Short_name": "Super, Store, Heroes", "Group_name": "Super Heroes Store"}

{"Group_members": [{"level": 1, "url": "http://www.bestbuy.com/site/Electronics/Mobile-Cell-Phones/abcat0800000.c?id=abcat0800000", "text": "Mobile Phones & iPhones", "site": "bestbuy", "parent_url": "http://www.bestbuy.com/site/sitemap.jsp#", "parent_text": "Products"}], "Level": 1, "Short_name": "Phones, Mobile, iPhones", "Group_name": "Mobile Phones & iPhones"}

