{"url": "http://www1.macys.com/shop/for-the-home?id=22672", "text": "Home Store", "level": 1}
{"url": "http://www1.macys.com/shop/bed-bath?id=7495", "text": "Bed & Bath", "level": 1}
{"url": "http://www1.macys.com/shop/womens?id=118", "text": "Women's Clothing", "level": 1}
{"url": "http://www1.macys.com/shop/mens?id=1", "text": "Men's Clothing", "level": 1}
{"url": "http://www1.macys.com/shop/juniors?id=16904", "text": "Juniors Clothing", "level": 1}
{"url": "http://www1.macys.com/shop/kids?id=5991", "text": "Kids Clothing", "level": 1}
{"url": "http://www1.macys.com/shop/beauty?id=669", "text": "Beauty & Fragrance", "level": 1}
{"url": "http://www1.macys.com/shop/shoes?id=13247", "text": "Shoe Store", "level": 1}
{"url": "http://www1.macys.com/shop/handbags-accessories?id=26846", "text": "Handbags & Accessories", "level": 1}
{"url": "http://www1.macys.com/shop/jewelry-watches?id=544", "text": "Jewelry & Watches", "level": 1}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=7495", "text": "Bed & Bath", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=7498", "text": "Dining & Entertaining", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=30599&PageID=176542055797845&kw=Holiday%20Lane", "text": "Holiday Lane", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=7497", "text": "Kitchen", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=16908", "text": "Luggage", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/haiti-rwanda-gifts?id=58181&edge=hybrid", "text": "Haiti & Rwanda Gifts", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/home-appliances?id=62056&edge=hybrid", "text": "Home Appliances", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/home-decor?id=55971&edge=hybrid", "text": "Home Decor", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/kids-baby-home?id=23484&edge=hybrid", "text": "Kids' & Baby Home", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/slipcovers?id=24672&edge=hybrid", "text": "Slipcovers", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/shoes/all-womens-shoes?id=56233&edge=hybrid", "text": "All Women's Shoes", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/for-the-home/summer-entertaining?id=34821&edge=hybrid", "text": "Summer Entertaining", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/window-treatments?id=26435&edge=hybrid", "text": "Window Treatments", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=127&channel_id=1", "text": "Custom Windows & Carpet", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=222&channel_id=1&cm_sp=searchbanner-_-college_lifestyle", "text": "Dorm Essentials", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/game-day-essentials?id=46291&edge=hybrid", "text": "Game Day Essentials", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/shoes/boots?id=25122&edge=hybrid", "text": "Boots", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/comfort?id=27902&edge=hybrid", "text": "Comfort", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/espadrilles-wedges?id=13808&edge=hybrid", "text": "Espadrilles & Wedges", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/evening-bridal?id=13614&edge=hybrid", "text": "Evening & Bridal", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=241&channel_id=1&bundle_entryPath", "text": "Macy's Heritage Shops", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/registry/wedding/registryhome", "text": "Wedding Registry", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=200&channel_id=1", "text": "The Wedding Shop", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/for-the-home/ready-to-assemble-furniture?id=65462&edge=hybrid", "text": "Ready-to-Assemble Furniture", "level": 0, "parent_text": "Home Store", "parent_url": "http://www1.macys.com/shop/for-the-home?id=22672"}
{"url": "http://www1.macys.com/shop/shoes/flats?id=50295&edge=hybrid", "text": "Flats", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/pumps?id=26481&edge=hybrid", "text": "Pumps", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/rain-boots?id=32459&edge=hybrid", "text": "Rain Boots", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/sandals?id=17570&edge=hybrid", "text": "Sandals", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/slippers?id=16108&edge=hybrid", "text": "Slippers", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/bed-bath/bath-rugs-bath-mats?id=8240&edge=hybrid", "text": "Bath Rugs & Bath Mats", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/handbags-accessories/all-handbags?id=27686&edge=hybrid", "text": "All Handbags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/shoes/sneakers?id=26499&edge=hybrid", "text": "Sneakers", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/juniors-shoes?id=57568&edge=hybrid", "text": "Juniors' Shoes", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=65", "text": "Men's Shoes", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/kids/featured/kids-shoes?id=48561&edge=hybrid", "text": "Kids' Shoes", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/bed-bath/bath-towels?id=16853&edge=hybrid", "text": "Bath Towels", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/bathroom-accessories?id=22094&edge=hybrid", "text": "Bathroom Accessories", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/shower-curtains-accessories?id=58936&edge=hybrid", "text": "Shower Curtains & Accessories", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/bedding-collections?id=7502&edge=hybrid", "text": "Bedding Collections", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/handbags-accessories/backpacks-laptop-bags?id=51906&edge=hybrid", "text": "Backpacks & Laptop Bags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/clutches-evening-bags?id=27691&edge=hybrid", "text": "Clutches & Evening Bags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/crossbody-messenger-bags?id=46011&edge=hybrid", "text": "Crossbody & Messenger Bags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/hobo-bags?id=46012&edge=hybrid", "text": "Hobo Bags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/satchels?id=46013&edge=hybrid", "text": "Satchels", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/shoes/business-shoes?id=58059&edge=hybrid", "text": "Business Shoes", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/designer-shoe-shop?id=50763&edge=hybrid", "text": "Designer Shoe Shop", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/shoes/shoe-trends?id=39395&edge=hybrid", "text": "Shoe Trends", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=200&channel_id=1", "text": "The Wedding Shop", "level": 0, "parent_text": "Shoe Store", "parent_url": "http://www1.macys.com/shop/shoes?id=13247"}
{"url": "http://www1.macys.com/shop/bed-bath/bed-in-a-bag?id=26795&edge=hybrid", "text": "Bed in a Bag", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/decorative-pillows?id=37945&edge=hybrid", "text": "Decorative Pillows", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/designer-comforters?id=20919&edge=hybrid", "text": "Designer Comforters", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/duvet-covers?id=25045&edge=hybrid", "text": "Duvet Covers", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/handbags-accessories/shoulder-bags?id=46014&edge=hybrid", "text": "Shoulder Bags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/tote-bags?id=46015&edge=hybrid", "text": "Tote Bags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/all-accessories?id=29440&edge=hybrid", "text": "All Accessories", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/belts?id=27807&edge=hybrid", "text": "Belts", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/hats-gloves-scarves?id=31957&edge=hybrid", "text": "Hats, Gloves & Scarves", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/jewelry-watches/all-watches?id=23930&edge=hybrid", "text": "All Watches", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/bed-bath/quilts-bedspreads?id=22748&edge=hybrid", "text": "Quilts & Bedspreads", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/apartment-bedding?id=60167&edge=hybrid", "text": "Apartment Bedding", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/dorm-bedding?id=60241&edge=hybrid", "text": "Dorm Bedding", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/luggage?id=16908&edge=hybrid", "text": "Luggage", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/tech-cases-accessories?id=32521&edge=hybrid", "text": "Tech Cases & Accessories", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/tights-socks?id=40546&edge=hybrid", "text": "Tights & Socks", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/travel-accessories?id=59720&edge=hybrid", "text": "Travel Accessories", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/jewelry-watches/bracelets?id=10834&edge=hybrid", "text": "Bracelets", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/earrings?id=10835&edge=hybrid", "text": "Earrings", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/necklaces?id=9569&edge=hybrid", "text": "Necklaces ", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/rings?id=21176&edge=hybrid", "text": "Rings", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/red-box-gifts?id=65291&edge=hybrid", "text": "Red Box Gifts", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/bed-bath/kids-bedding?id=13661&edge=hybrid", "text": "Kids' Bedding", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/teen-bedding?id=12398&edge=hybrid", "text": "Teen Bedding", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/bed-canopies?id=49492&edge=hybrid", "text": "Bed Canopies", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/blankets-throws?id=29405&edge=hybrid", "text": "Blankets & Throws", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/down-comforters?id=28898&edge=hybrid", "text": "Down Comforters", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/handbags-accessories/umbrellas?id=28225&edge=hybrid", "text": "Umbrellas", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/wallets-wristlets?id=27689&edge=hybrid", "text": "Wallets & Wristlets", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/handbag-trends?id=28265&edge=hybrid", "text": "Handbag Trends", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/handbags-accessories/impulse-brands?id=53610&edge=hybrid", "text": "Impulse Handbags", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/jewelry-watches/charms?id=63914&edge=hybrid", "text": "Charms", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/diamonds?id=57702&edge=hybrid", "text": "Diamonds", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/gemstones?id=2903&edge=hybrid", "text": "Gemstones", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/gold?id=2904&edge=hybrid", "text": "Gold", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/pearls?id=2905&edge=hybrid", "text": "Pearls", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/bed-bath/feather-beds-fiberbeds?id=28899&edge=hybrid", "text": "Feather Beds & Fiberbeds", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/mattress-pads-toppers?id=40384&edge=hybrid", "text": "Mattress Pads & Toppers", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/memory-foam-bedding?id=29483&edge=hybrid", "text": "Memory Foam Bedding", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/pillows?id=28901&edge=hybrid", "text": "Pillows", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/shop/bed-bath/sheets?id=9915&edge=hybrid", "text": "Sheets", "level": 0, "parent_text": "Bed & Bath", "parent_url": "http://www1.macys.com/shop/bed-bath?id=7495"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=200&channel_id=1", "text": "The Wedding Shop", "level": 0, "parent_text": "Handbags & Accessories", "parent_url": "http://www1.macys.com/shop/handbags-accessories?id=26846"}
{"url": "http://www1.macys.com/shop/jewelry-watches/wedding-engagement-rings?id=60053&edge=hybrid", "text": "Wedding & Engagement Rings", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/all-fashion-jewelry?id=55352&edge=hybrid", "text": "All Fashion Jewelry", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/fashion-bracelets?id=55286&edge=hybrid", "text": "Fashion Bracelets", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/fashion-earrings?id=55287&edge=hybrid", "text": "Fashion Earrings", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/fashion-necklaces?id=55288&edge=hybrid", "text": "Fashion Necklaces", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/fashion-rings?id=55289&edge=hybrid", "text": "Fashion Rings", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/fall-jewelry-trends?id=55391&edge=hybrid", "text": "Fall Jewelry Trends", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/silver-bracelets?id=545&edge=hybrid", "text": "Silver Bracelets", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/silver-earrings?id=555&edge=hybrid", "text": "Silver Earrings", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/silver-necklaces?id=566&edge=hybrid", "text": "Silver Necklaces", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/silver-rings?id=550&edge=hybrid", "text": "Silver Rings", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/impulse-jewelry?id=42041&edge=hybrid", "text": "Impulse Jewelry", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/jewelry-boxes-accessories?id=55305&edge=hybrid", "text": "Jewelry Boxes & Accessories", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/kids-jewelry-watches?id=33222&edge=hybrid", "text": "Kids' Jewelry & Watches", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/jewelry-watches/mens-jewelry-accessories?id=43877&edge=hybrid", "text": "Men's Jewelry & Accessories", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=200&channel_id=1&bundle_entryPath=jewelry", "text": "The Wedding Shop", "level": 0, "parent_text": "Jewelry & Watches", "parent_url": "http://www1.macys.com/shop/jewelry-watches?id=544"}
{"url": "http://www1.macys.com/shop/juniors-clothing/activewear?id=41973&edge=hybrid", "text": "Activewear", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-coats?id=21115&edge=hybrid", "text": "Coats", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-dresses?id=18109&edge=hybrid", "text": "Dresses", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-jackets?id=35786&edge=hybrid", "text": "Jackets & Vests", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-jeans?id=28754&edge=hybrid", "text": "Jeans", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-jumpsuits-rompers?id=17053&edge=hybrid", "text": "Jumpsuits & Rompers", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/womens/apparel/lingerie/special-sizes/juniors?id=56273&edge=hybrid", "text": "Lingerie & Pajamas", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-pants?id=21561&edge=hybrid", "text": "Pants & Capris", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-shorts?id=28589&edge=hybrid", "text": "Shorts", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-skirts?id=28379&edge=hybrid", "text": "Skirts", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-suits?id=28001&edge=hybrid", "text": "Suits & Suit Separates", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-sweaters?id=20853&edge=hybrid", "text": "Sweaters", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/juniors-swimwear?id=57597&edge=hybrid", "text": "Swimwear", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-tops?id=17043&edge=hybrid", "text": "Tops", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/plus-size-clothing/junior-plus-size?id=32918&edge=hybrid", "text": "Junior Plus Sizes", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=342&channel_id=1&bundle_entryPath=/home/girls", "text": "Fall Style Mixer", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/festival-fashion?id=63651&edge=hybrid", "text": "Festival Fashion", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/homecoming-dress-shop?id=61088&edge=hybrid", "text": "Homecoming Dresses", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=202&channel_id=1&bundle_entryPath=/womenHome", "text": "Impulse Contemporary Trends", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/mstylelab-brands?id=57569&edge=hybrid", "text": "mstylelab Brands", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/shop-all-juniors-apparel?id=60983&edge=hybrid#!fn=sortBy%3DNEW_ITEMS%26productsPerPage%3D40&!qvp=iqvp", "text": "Summer New Arrivals", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/handbags-accessories/mstylelab-brands?id=54525&edge=hybrid", "text": "Handbags & Accessories", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing/juniors-jewelry?id=30713&edge=hybrid", "text": "Jewelry & Watches", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/shoes/shop/junior-shoes?id=57568&edge=hybrid", "text": "Shoes", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/handbags-accessories/accessories/sunglasses?id=58128&edge=hybrid", "text": "Sunglasses", "level": 0, "parent_text": "Juniors Clothing", "parent_url": "http://www1.macys.com/shop/juniors-clothing?id=16904&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-activewear?id=29891&edge=hybrid", "text": "Activewear", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-coats?id=269&edge=hybrid", "text": "Coats", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/dresses?id=5449&edge=hybrid", "text": "Dresses", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-jackets?id=120&edge=hybrid", "text": "Jackets & Blazers", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-jeans?id=3111&edge=hybrid", "text": "Jeans", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-jumpsuits-rompers?id=50684&edge=hybrid", "text": "Jumpsuits & Rompers", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/big-and-tall?id=45758&edge=hybrid", "text": "Big & Tall", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-leggings?id=46905&edge=hybrid", "text": "Leggings", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/lingerie?id=225&edge=hybrid", "text": "Lingerie", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens/apparel/lingerie/pajamas-robes?id=59737&edge=hybrid", "text": "Pajamas & Robes", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-pants?id=157&edge=hybrid", "text": "Pants & Capris", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-shorts?id=5344&edge=hybrid", "text": "Shorts", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/beauty/shop-by-category/cologne-grooming?id=30088&edge=hybrid", "text": "Cologne & Grooming", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/guys-clothing?id=60451&edge=hybrid", "text": "Guys", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-shoes?id=65&edge=hybrid", "text": "Shoes", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-activewear?id=3296&edge=hybrid", "text": "Activewear", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-skirts?id=131&edge=hybrid", "text": "Skirts", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-suits?id=39096&edge=hybrid", "text": "Suits & Suit Separates", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-sweaters?id=260&edge=hybrid", "text": "Sweaters", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-swimwear?id=8699&edge=hybrid", "text": "Swimwear", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-tops?id=255&edge=hybrid", "text": "Tops", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-blazers?id=16499&edge=hybrid", "text": "Blazers & Sport Coats", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-casual-shirts?id=20627&edge=hybrid", "text": "Casual Button-Down Shirts ", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-coats?id=3763&edge=hybrid", "text": "Coats & Jackets", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-dress-shirts?id=20635&edge=hybrid", "text": "Dress Shirts ", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/hoodies-for-men?id=25995&edge=hybrid", "text": "Hoodies & Fleece", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/juniors-clothing?id=16904&edge=hybrid", "text": "Juniors", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/plus-size-clothing/junior-plus-size-clothing?id=32918", "text": "Junior Plus Sizes", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/petite-clothing?id=18579&edge=hybrid", "text": "Petite", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/plus-size-clothing?id=32147&edge=hybrid", "text": "Plus Sizes", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/womens-cashmere-sweater-shop?id=262", "text": "Cashmere Shop", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-jeans?id=11221&edge=hybrid", "text": "Jeans", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-pajamas?id=16295&edge=hybrid", "text": "Pajamas & Robes", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-pants?id=89&edge=hybrid", "text": "Pants", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-polos?id=20640&edge=hybrid", "text": "Polos", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=202&channel_id=1&bundle_entryPath=/womenHome", "text": "Impulse Contemporary Trends", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=200&channel_id=1", "text": "The Wedding Shop", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/m/campaign/trendreport/black-and-white-rtw", "text": "Wear Now, Wear Later", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/m/campaign/trendreport/work-your-wardrobe-fall2013/rtw/index", "text": "Work Wardrobe Guide", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/helly-hansen?id=64841", "text": "Helly Hansen", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-shirts?id=20626&edge=hybrid", "text": "Shirts", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-shorts?id=3310&edge=hybrid", "text": "Shorts", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-suits?id=17788&edge=hybrid", "text": "Suits & Suit Separates", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-sweaters?id=4286&edge=hybrid", "text": "Sweaters", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-swimwear?id=3291&edge=hybrid", "text": "Swimwear", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/womens-clothing/the-pink-shop?id=65297&edge=hybrid", "text": "The Pink Shop", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=26846", "text": "Handbags & Accessories", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/handbags-accessories/hats-gloves-scarves?id=31957&edge=hybrid", "text": "Hats, Gloves & Scarves", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=13247", "text": "Shoes", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/ties?id=53239&edge=hybrid", "text": "Ties", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-t-shirts?id=30423&edge=hybrid", "text": "T-Shirts", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-underwear?id=57&edge=hybrid", "text": "Underwear ", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-bags?id=45016&edge=hybrid", "text": "Bags & Backpacks", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/handbags-accessories/accessories/sunglasses?id=58128&edge=hybrid", "text": "Sunglasses", "level": 0, "parent_text": "Women's Clothing", "parent_url": "http://www1.macys.com/shop/womens-clothing?id=118&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-belts?id=47665&edge=hybrid", "text": "Belts, Wallets & Accessories", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/hats-gloves-scarves?id=47657&edge=hybrid", "text": "Hats, Gloves & Scarves", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-shoes?id=65&edge=hybrid", "text": "Shoes", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mens-socks?id=18245&edge=hybrid", "text": "Socks", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/jewelry-watches/watches/all-watches/gender/mens-watches?id=57386&edge=hybrid", "text": "Watches", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/finish-line?id=63266&edge=hybrid&cm_sp=navigation-_-top_nav-_-1_mens", "text": "Finish Line Athletic Shoes", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=202&channel_id=1&bundle_entryPath=/men-home", "text": "Impulse Trends", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=159&channel_id=1", "text": "Men's Guide to Style", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/mstylelab?id=61530&edge=hybrid", "text": "mstylelab", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/sports-apparel?id=48050&edge=hybrid", "text": "Sports Fan Shop", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=200&channel_id=1", "text": "The Wedding Shop", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/surf-skate?id=61123&edge=hybrid", "text": "Surf & Skate", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/slim-fit-shop?id=62437&edge=hybrid", "text": "Slim Fit Shop", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/bar-iii-carnaby?id=65157&edge=hybrid", "text": "Bar III Carnaby", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/shop/mens-clothing/helly-hansen?id=64942&edge=hybrid", "text": "Helly Hansen", "level": 0, "parent_text": "Men's Clothing", "parent_url": "http://www1.macys.com/shop/mens-clothing?id=1&intnl=true"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=48692", "text": "Baby Girl (0-24 months)", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=48693", "text": "Baby Boy (0-24 months)", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=59563", "text": "Newborn Shop", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/toddler-girl-clothes?id=6581&edge=hybrid", "text": "Toddler Girls (2T-5T)", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/girls-2-6x?id=62970&edge=hybrid", "text": "Girls 2-6X", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/big-girl-clothes-7-16?id=25324&edge=hybrid", "text": "Girls 7-16", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/toddler-boy-clothes?id=27058&edge=hybrid", "text": "Toddler Boys (2T-5T)", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/boys-2-7?id=62971&edge=hybrid", "text": "Boys 2-7", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/big-boy-clothes-8-20?id=25325&edge=hybrid", "text": "Boys 8-20", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/accessories?id=63009&edge=hybrid", "text": "Accessories", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/kids-activewear?id=61228&edge=hybrid", "text": "Activewear", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/dresses-dresswear?id=63016&edge=hybrid", "text": "Dresses & Dresswear", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/jackets-coats?id=63010&edge=hybrid", "text": "Jackets & Coats", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/jeans?id=63008&edge=hybrid", "text": "Jeans", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/pants?id=63011&edge=hybrid", "text": "Pants", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/pajamas?id=65451&edge=hybrid", "text": "Pajamas", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/sets?id=63013&edge=hybrid", "text": "Sets", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/shirts-tees?id=63014&edge=hybrid", "text": "Shirts & Tees", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/shorts?id=63015&edge=hybrid", "text": "Shorts", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/socks-underwear?id=65582&edge=hybrid", "text": "Socks & Underwear", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/sweaters?id=65543&edge=hybrid", "text": "Sweaters", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/kids-swimwear?id=55163&edge=hybrid", "text": "Swimwear", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/bed-bath/kids-teen-bedding/kids-bedding-bath?id=13661&edge=hybrid", "text": "Kids' Bedding & Bath", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/catalog/index.ognc?CategoryID=33222", "text": "Kids' Jewelry & Watches", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/kids-special-occasion-clothing?id=26073&edge=hybrid", "text": "Kids' Special Occasion", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/kids-shoes?id=48561&edge=hybrid", "text": "Kids' Shoes", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/campaign/social?campaign_id=231&channel_id=1", "text": "Kids' Back to School Collection", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/school-uniforms?id=30057&edge=hybrid", "text": "School Uniforms", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
{"url": "http://www1.macys.com/shop/kids-clothes/kids-games-toys?id=22911&edge=hybrid", "text": "Toys & Games", "level": 0, "parent_text": "Kids Clothing", "parent_url": "http://www1.macys.com/shop/kids-clothes?id=5991&intnl=true"}
