{"page_title": "Decorator 28x28-inch Euro Square Pillows (Set of 2)", "url": "http://www.overstock.com/Bedding-Bath/Decorator-28x28-inch-Euro-Square-Pillows-Set-of-2/4493223/product.html?IID=prod4493223&sec_iid=78178", "price": "RON              180.87", "rank": "6", "department": "Bedding", "list_name": "Decorator 28x28-inch Euro Square Pillows (Set of 2)", "product_name": "Decorator 28x28-inch Euro Square Pillows (Set of 2)"}
{"page_title": "Priage Green Tea/ Charcoal 6-inch Full-size Memory Foam  Mattress", "url": "http://www.overstock.com/Home-Garden/Priage-Green-Tea-Charcoal-6-inch-Full-size-Memory-Foam-Mattress/6756786/product.html?IID=prod6756786&sec_iid=78178", "price": "RON              904.47", "rank": "10", "department": "Bedding", "list_name": "Priage Green Tea/ Charcoal 6-inch Full-size Memory Foam Mattress", "product_name": "Priage Green Tea/ Charcoal 6-inch Full-size Memory Foam  Mattress"}
{"page_title": "Quilted Top 10-inch Twin-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Quilted-Top-10-inch-Twin-size-Memory-Foam-Mattress/6044992/product.html?IID=prod6044992&sec_iid=78178", "price": "RON              1001.45", "rank": "9", "department": "Bedding", "list_name": "Quilted Top 10-inch Twin-size Memory Foam Mattress", "product_name": "Quilted Top 10-inch Twin-size Memory Foam Mattress"}
{"page_title": "Slumber Solutions Gel Memory Foam 8-inch Queen-size Mattress", "url": "http://www.overstock.com/Home-Garden/Slumber-Solutions-Gel-Memory-Foam-8-inch-Queen-size-Mattress/6995871/product.html?IID=prod6995871&sec_iid=78178", "price": "RON              1334.08", "rank": "3", "department": "Bedding", "list_name": "Slumber Solutions Gel Memory Foam 8-inch Queen-size Mattress", "product_name": "Slumber Solutions Gel Memory Foam 8-inch Queen-size Mattress"}
{"page_title": "Quilted Top 10-inch Full-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Quilted-Top-10-inch-Full-size-Memory-Foam-Mattress/6055956/product.html?IID=prod6055956&sec_iid=78178", "price": "RON              1198.39", "rank": "2", "department": "Bedding", "list_name": "Quilted Top 10-inch Full-size Memory Foam Mattress", "product_name": "Quilted Top 10-inch Full-size Memory Foam Mattress"}
{"page_title": "Select Luxury Reversible Medium Firm 10-Inch Full-Size Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Select-Luxury-Reversible-Medium-Firm-10-Inch-Full-Size-Foam-Mattress/6373328/product.html?IID=prod6373328&sec_iid=78178", "price": "RON              1406.97", "rank": "5", "department": "Bedding", "list_name": "Select Luxury Reversible Medium Firm 10-Inch Full-Size Foam Mattress", "product_name": "Select Luxury Reversible Medium Firm 10-Inch Full-Size Foam Mattress"}
{"page_title": "Bodipedic Essentials 8-inch Queen-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Bodipedic-Essentials-8-inch-Queen-size-Memory-Foam-Mattress/6153386/product.html?IID=prod6153386&sec_iid=78178", "price": "RON              1507.47", "rank": "4", "department": "Bedding", "list_name": "Bodipedic Essentials 8-inch Queen-size Memory Foam Mattress", "product_name": "Bodipedic Essentials 8-inch Queen-size Memory Foam Mattress"}
{"page_title": "Comfort Dreams Select-A-Firmness 11-inch Queen-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Comfort-Dreams-Select-A-Firmness-11-inch-Queen-size-Memory-Foam-Mattress/3158654/product.html?IID=prod3158654&sec_iid=78178", "price": "RON              2009.97", "rank": "1", "department": "Bedding", "list_name": "Comfort Dreams Select-A-Firmness 11-inch Queen-size Memory Foam Mattress", "product_name": "Comfort Dreams Select-A-Firmness 11-inch Queen-size Memory Foam Mattress"}
{"page_title": "Ray-Ban Unisex RB2132 Wayfarer Fashion Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-Unisex-RB2132-Wayfarer-Fashion-Sunglasses/5173946/product.html?IID=prod5173946&sec_iid=78178", "price": "RON              405.49", "rank": "1", "department": "Clothing", "list_name": "Ray-Ban Unisex RB2132 Wayfarer Fashion Sunglasses", "product_name": "Ray-Ban Unisex RB2132 Wayfarer Fashion Sunglasses"}
{"page_title": "Grande Hotel Collection Posture Support 8-inch Queen-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Grande-Hotel-Collection-Posture-Support-8-inch-Queen-size-Memory-Foam-Mattress/6055686/product.html?IID=prod6055686&sec_iid=78178", "price": "RON              1356.70", "rank": "12", "department": "Bedding", "list_name": "Grande Hotel Collection Posture Support 8-inch Queen-size Memory Foam Mattress", "product_name": "Grande Hotel Collection Posture Support 8-inch Queen-size Memory Foam Mattress"}
{"page_title": "Comfort Dreams Select-A-Firmness 11-inch Full-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Comfort-Dreams-Select-A-Firmness-11-inch-Full-size-Memory-Foam-Mattress/3158653/product.html?IID=prod3158653&sec_iid=78178", "price": "RON              1788.87", "rank": "7", "department": "Bedding", "list_name": "Comfort Dreams Select-A-Firmness 11-inch Full-size Memory Foam Mattress", "product_name": "Comfort Dreams Select-A-Firmness 11-inch Full-size Memory Foam Mattress"}
{"page_title": "Select Luxury Medium Firm 14-inch King-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Select-Luxury-Medium-Firm-14-inch-King-size-Memory-Foam-Mattress/5977720/product.html?IID=prod5977720&sec_iid=78178", "price": "RON              2944.61", "rank": "8", "department": "Bedding", "list_name": "Select Luxury Medium Firm 14-inch King-size Memory Foam Mattress", "product_name": "Select Luxury Medium Firm 14-inch King-size Memory Foam Mattress"}
{"page_title": "Grace Elements Women's Studded Tank Top", "url": "http://www.overstock.com/Clothing-Shoes/Grace-Elements-Womens-Studded-Tank-Top/6839950/product.html?IID=prod6839950&sec_iid=78178", "price": "RON              100.46", "rank": "5", "department": "Clothing", "list_name": "Grace Elements Women's Studded Tank Top", "product_name": "Grace Elements Women's Studded Tank Top"}
{"page_title": "Grande Hotel Collection Posture Support 14-inch King-size Trizone Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Grande-Hotel-Collection-Posture-Support-14-inch-King-size-Trizone-Memory-Foam-Mattress/6055705/product.html?IID=prod6055705&sec_iid=78178", "price": "RON              3316.48", "rank": "11", "department": "Bedding", "list_name": "Grande Hotel Collection Posture Support 14-inch King-size Trizone Memory Foam Mattress", "product_name": "Grande Hotel Collection Posture Support 14-inch King-size Trizone Memory Foam Mattress"}
{"page_title": "Ray-Ban 'RB2132 New Wayfarer' 902L Havana Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-RB2132-New-Wayfarer-902L-Havana-Sunglasses/6611196/product.html?IID=prod6611196&sec_iid=78178", "price": "RON              432.10", "rank": "3", "department": "Clothing", "list_name": "Ray-Ban 'RB2132 New Wayfarer' 902L Havana Sunglasses", "product_name": "Ray-Ban 'RB2132 New Wayfarer' 902L Havana Sunglasses"}
{"page_title": "Luxurious Egyptian Cotton Unisex Terry Bath Robe", "url": "http://www.overstock.com/Bedding-Bath/Luxurious-Egyptian-Cotton-Unisex-Terry-Bath-Robe/6632152/product.html?IID=prod6632152&sec_iid=78178", "price": "RON              168.59", "rank": "4", "department": "Clothing", "list_name": "Luxurious Egyptian Cotton Unisex Terry Bath Robe", "product_name": "Luxurious Egyptian Cotton Unisex Terry Bath Robe"}
{"page_title": "BasAcc Black Leather Swivel Case for Apple iPad Mini", "url": "http://www.overstock.com/Electronics/BasAcc-Black-Leather-Swivel-Case-for-Apple-iPad-Mini/7509874/product.html?IID=prod7509874&sec_iid=78178", "price": "RON              34.47", "rank": "12", "department": "Electronics", "list_name": "BasAcc Black Leather Swivel Case for Apple iPad Mini", "product_name": "BasAcc Black Leather Swivel Case for Apple iPad Mini"}
{"page_title": "Black Leather Case for Samsung Galaxy Tab 2 P3100/ P3110/ 7-inch", "url": "http://www.overstock.com/Electronics/Black-Leather-Case-for-Samsung-Galaxy-Tab-2-P3100-P3110-7-inch/6986714/product.html?IID=prod6986714&sec_iid=78178", "price": "RON              32.59", "rank": "11", "department": "Electronics", "list_name": "Black Leather Case for Samsung Galaxy Tab 2 P3100/ P3110/ 7-inch", "product_name": "Black Leather Case for Samsung Galaxy Tab 2 P3100/ P3110/ 7-inch"}
{"page_title": "Black/ Pink Dot Wallet Leather Case for Apple iPhone 4/ 4S", "url": "http://www.overstock.com/Electronics/Black-Pink-Dot-Wallet-Leather-Case-for-Apple-iPhone-4-4S/6493967/product.html?IID=prod6493967&sec_iid=78178", "price": "RON              22.45", "rank": "10", "department": "Electronics", "list_name": "Black/ Pink Dot Wallet Leather Case for Apple iPhone 4/ 4S", "product_name": "Black/ Pink Dot Wallet Leather Case for Apple iPhone 4/ 4S"}
{"page_title": "Highland Mission Oak Media Stand", "url": "http://www.overstock.com/Home-Garden/Highland-Mission-Oak-Media-Stand/4334806/product.html?IID=prod4334806&sec_iid=78178", "price": "RON              1424.55", "rank": "7", "department": "Electronics", "list_name": "Highland Mission Oak Media Stand", "product_name": "Highland Mission Oak Media Stand"}
{"page_title": "BasAcc Case/ Protector/ Charger/ Stylus for Amazon Kindle Fire HD", "url": "http://www.overstock.com/Electronics/BasAcc-Case-Protector-Charger-Stylus-for-Amazon-Kindle-Fire-HD/7675906/product.html?IID=prod7675906&sec_iid=78178", "price": "RON              52.69", "rank": "8", "department": "Electronics", "list_name": "BasAcc Case/ Protector/ Charger/ Stylus for Amazon Kindle Fire HD", "product_name": "BasAcc Case/ Protector/ Charger/ Stylus for Amazon Kindle Fire HD"}
{"page_title": "HP 6005 PRO 3.0GHz 8GB 1.5TB Win 7 Small Form Factor Computer (Refurbished)", "url": "http://www.overstock.com/Electronics/HP-6005-PRO-3.0GHz-8GB-1.5TB-Win-7-Small-Form-Factor-Computer-Refurbished/8009646/product.html?IID=prod8009646&sec_iid=78178", "price": "RON              1507.51", "rank": "9", "department": "Electronics", "list_name": "HP 6005 PRO 3.0GHz 8GB 1.5TB Win 7 Small Form Factor Computer (Refurbished)", "product_name": "HP 6005 PRO 3.0GHz 8GB 1.5TB Win 7 Small Form Factor Computer (Refurbished)"}
{"page_title": "Retro Phone Handset for Apple iPhone 5, 4/4S iPad 2/ iPad 3/ iPad mini", "url": "http://www.overstock.com/Electronics/Retro-Phone-Handset-for-Apple-iPhone-5-4-4S-iPad-2-iPad-3-iPad-mini/6267585/product.html?IID=prod6267585&sec_iid=78178", "price": "RON              40.16", "rank": "6", "department": "Electronics", "list_name": "Retro Phone Handset for Apple iPhone 5, 4/4S iPad 2/ iPad 3/ iPad mini", "product_name": "Retro Phone Handset for Apple iPhone 5, 4/4S iPad 2/ iPad 3/ iPad mini"}
{"page_title": "Lawrence Entertainment Center", "url": "http://www.overstock.com/Home-Garden/Lawrence-Entertainment-Center/4273819/product.html?IID=prod4273819&sec_iid=78178", "price": "RON              2227.55", "rank": "5", "department": "Electronics", "list_name": "Lawrence Entertainment Center", "product_name": "Lawrence Entertainment Center"}
{"page_title": "BasAcc Hybrid Case for Apple iPhone 4/ 4S", "url": "http://www.overstock.com/Electronics/BasAcc-Hybrid-Case-for-Apple-iPhone-4-4S/7322770/product.html?IID=prod7322770&sec_iid=78178", "price": "RON              18.82", "rank": "4", "department": "Electronics", "list_name": "BasAcc Hybrid Case for Apple iPhone 4/ 4S", "product_name": "BasAcc Hybrid Case for Apple iPhone 4/ 4S"}
{"page_title": "Four-inch Universal Touch Screen Stylus Set (Pack of Three)", "url": "http://www.overstock.com/Electronics/Four-inch-Universal-Touch-Screen-Stylus-Set-Pack-of-Three/6470748/product.html?IID=prod6470748&sec_iid=78178", "price": "RON              15.05", "rank": "2", "department": "Electronics", "list_name": "Four-inch Universal Touch Screen Stylus Set (Pack of Three)", "product_name": "Four-inch Universal Touch Screen Stylus Set (Pack of Three)"}
{"page_title": "Matlock Modern Glass Door TV Stand", "url": "http://www.overstock.com/Home-Garden/Matlock-Modern-Glass-Door-TV-Stand/6162021/product.html?IID=prod6162021&sec_iid=78178", "price": "RON              1123.79", "rank": "3", "department": "Electronics", "list_name": "Matlock Modern Glass Door TV Stand", "product_name": "Matlock Modern Glass Door TV Stand"}
{"page_title": "MyBat Apple iPhone 4S/4 Hybrid Protector Cover", "url": "http://www.overstock.com/Electronics/MyBat-Apple-iPhone-4S-4-Hybrid-Protector-Cover/6797433/product.html?IID=prod6797433&sec_iid=78178", "price": "RON              25.08", "rank": "1", "department": "Electronics", "list_name": "MyBat Apple iPhone 4S/4 Hybrid Protector Cover", "product_name": "MyBat Apple iPhone 4S/4 Hybrid Protector Cover"}
{"page_title": "Parachute Silk Waterproof Two-person Hammock with Stuff Sack", "url": "http://www.overstock.com/Sports-Toys/Parachute-Silk-Waterproof-Two-person-Hammock-with-Stuff-Sack/4835102/product.html?IID=prod4835102&sec_iid=78178", "price": "RON              198.44", "rank": "12", "department": "Sports", "list_name": "Parachute Silk Waterproof Two-person Hammock with Stuff Sack", "product_name": "Parachute Silk Waterproof Two-person Hammock with Stuff Sack"}
{"page_title": "Coleman Heritage Big and Tall Sleeping Bag", "url": "http://www.overstock.com/Sports-Toys/Coleman-Heritage-Big-and-Tall-Sleeping-Bag/7856296/product.html?IID=prod7856296&sec_iid=78178", "price": "RON              346.65", "rank": "10", "department": "Sports", "list_name": "Coleman Heritage Big and Tall Sleeping Bag", "product_name": "Coleman Heritage Big and Tall Sleeping Bag"}
{"page_title": "Exerpeutic 400XL Folding Semi Recumbent Exercise Bike", "url": "http://www.overstock.com/Sports-Toys/Exerpeutic-400XL-Folding-Semi-Recumbent-Exercise-Bike/5700682/product.html?IID=prod5700682&sec_iid=78178", "price": "RON              748.68", "rank": "11", "department": "Sports", "list_name": "Exerpeutic 400XL Folding Semi Recumbent Exercise Bike", "product_name": "Exerpeutic 400XL Folding Semi Recumbent Exercise Bike"}
{"page_title": "Trijicon RMR 3.25 MOA Red Dot LED Sight", "url": "http://www.overstock.com/Sports-Toys/Trijicon-RMR-3.25-MOA-Red-Dot-LED-Sight/4413037/product.html?IID=prod4413037&sec_iid=78178", "price": "RON              2669.54", "rank": "8", "department": "Sports", "list_name": "Trijicon RMR 3.25 MOA Red Dot LED Sight", "product_name": "Trijicon RMR 3.25 MOA Red Dot LED Sight"}
{"page_title": "Caravan Canopy Black Zero-Gravity Chairs (Pack of Two)", "url": "http://www.overstock.com/Sports-Toys/Caravan-Canopy-Black-Zero-Gravity-Chairs-Pack-of-Two/5336679/product.html?IID=prod5336679&sec_iid=78178", "price": "RON              502.47", "rank": "9", "department": "Sports", "list_name": "Caravan Canopy Black Zero-Gravity Chairs (Pack of Two)", "product_name": "Caravan Canopy Black Zero-Gravity Chairs (Pack of Two)"}
{"page_title": "Caravan Canopy Blue Zero-Gravity Chairs (Pack of Two)", "url": "http://www.overstock.com/Sports-Toys/Caravan-Canopy-Blue-Zero-Gravity-Chairs-Pack-of-Two/5333767/product.html?IID=prod5333767&sec_iid=78178", "price": "RON              502.47", "rank": "5", "department": "Sports", "list_name": "Caravan Canopy Blue Zero-Gravity Chairs (Pack of Two)", "product_name": "Caravan Canopy Blue Zero-Gravity Chairs (Pack of Two)"}
{"page_title": "Serta Raised Queen-size Airbed with Insta III AC Pump", "url": "http://www.overstock.com/Home-Garden/Serta-Raised-Queen-size-Airbed-with-Insta-III-AC-Pump/6609121/product.html?IID=prod6609121&sec_iid=78178", "price": "RON              602.97", "rank": "6", "department": "Sports", "list_name": "Serta Raised Queen-size Airbed with Insta III AC Pump", "product_name": "Serta Raised Queen-size Airbed with Insta III AC Pump"}
{"page_title": "Discovery Kids Cardboard Color and Play Playhouse", "url": "http://www.overstock.com/Sports-Toys/Discovery-Kids-Cardboard-Color-and-Play-Playhouse/6982020/product.html?IID=prod6982020&sec_iid=78178", "price": "RON              130.60", "rank": "3", "department": "Sports", "list_name": "Discovery Kids Cardboard Color and Play Playhouse", "product_name": "Discovery Kids Cardboard Color and Play Playhouse"}
{"page_title": "TheraSpa 4-person Inflatable Portable Hot Tub Spa", "url": "http://www.overstock.com/Sports-Toys/TheraSpa-4-person-Inflatable-Portable-Hot-Tub-Spa/6499764/product.html?IID=prod6499764&sec_iid=78178", "price": "RON              2487.36", "rank": "7", "department": "Sports", "list_name": "TheraSpa 4-person Inflatable Portable Hot Tub Spa", "product_name": "TheraSpa 4-person Inflatable Portable Hot Tub Spa"}
{"page_title": "Ironman Gravity 4000 Inversion Table with Memory Foam", "url": "http://www.overstock.com/Sports-Toys/Ironman-Gravity-4000-Inversion-Table-with-Memory-Foam/3352203/product.html?IID=prod3352203&sec_iid=78178", "price": "RON              974.87", "rank": "4", "department": "Sports", "list_name": "Ironman Gravity 4000 Inversion Table with Memory Foam", "product_name": "Ironman Gravity 4000 Inversion Table with Memory Foam"}
{"page_title": "ProMag Ruger LCP 10-round Pistol Magazine", "url": "http://www.overstock.com/Sports-Toys/ProMag-Ruger-LCP-10-round-Pistol-Magazine/5241623/product.html?IID=prod5241623&sec_iid=78178", "price": "RON              135.65", "rank": "1", "department": "Sports", "list_name": "ProMag Ruger LCP 10-round Pistol Magazine", "product_name": "ProMag Ruger LCP 10-round Pistol Magazine"}
{"page_title": "Caravan Canopy Beige Zero-Gravity Chairs (Pack of Two)", "url": "http://www.overstock.com/Sports-Toys/Caravan-Canopy-Beige-Zero-Gravity-Chairs-Pack-of-Two/5333766/product.html?IID=prod5333766&sec_iid=78178", "price": "RON              502.47", "rank": "2", "department": "Sports", "list_name": "Caravan Canopy Beige Zero-Gravity Chairs (Pack of Two)", "product_name": "Caravan Canopy Beige Zero-Gravity Chairs (Pack of Two)"}
{"page_title": "Honeycomb Cell Blackout White Cordless Cellular Shades", "url": "http://www.overstock.com/Home-Garden/Honeycomb-Cell-Blackout-White-Cordless-Cellular-Shades/5903809/product.html?IID=prod5903809&sec_iid=78178", "price": "RON              226.08", "rank": "12", "department": "Home & Garden", "list_name": "Honeycomb Cell Blackout White Cordless Cellular Shades", "product_name": "Honeycomb Cell Blackout White Cordless Cellular Shades"}
{"page_title": "Cozy Beige Shag Rug (8' x 10')", "url": "http://www.overstock.com/Home-Garden/Cozy-Beige-Shag-Rug-8-x-10/5953871/product.html?IID=prod5953871&sec_iid=78178", "price": "RON              1376.80", "rank": "10", "department": "Home & Garden", "list_name": "Cozy Beige Shag Rug (8' x 10')", "product_name": "Cozy Beige Shag Rug (8' x 10')"}
{"page_title": "Hand-hooked Alexa Moroccan Trellis Wool Rug (7'6 x 9'6)", "url": "http://www.overstock.com/Home-Garden/Hand-hooked-Alexa-Moroccan-Trellis-Wool-Rug-76-x-96/5777733/product.html?IID=prod5777733&sec_iid=78178", "price": "RON              1683.36", "rank": "11", "department": "Home & Garden", "list_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (7'6 x 9'6)", "product_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (7'6 x 9'6)"}
{"page_title": "Handmade Luna Marrakesh Trellis Wool Rug (5' x 8')", "url": "http://www.overstock.com/Home-Garden/Handmade-Luna-Marrakesh-Trellis-Wool-Rug-5-x-8/6437411/product.html?IID=prod6437411&sec_iid=78178", "price": "RON              934.60", "rank": "9", "department": "Home & Garden", "list_name": "Handmade Luna Marrakesh Trellis Wool Rug (5' x 8')", "product_name": "Handmade Luna Marrakesh Trellis Wool Rug (5' x 8')"}
{"page_title": "Cotton Duck Sofa Slipcover", "url": "http://www.overstock.com/Home-Garden/Cotton-Duck-Sofa-Slipcover/628264/product.html?IID=prod628264&sec_iid=78178", "price": "RON              286.38", "rank": "8", "department": "Home & Garden", "list_name": "Cotton Duck Sofa Slipcover", "product_name": "Cotton Duck Sofa Slipcover"}
{"page_title": "Supreme Felted Dual Surface Rug Pad (8' x 10')", "url": "http://www.overstock.com/Home-Garden/Supreme-Felted-Dual-Surface-Rug-Pad-8-x-10/5721573/product.html?IID=prod5721573&sec_iid=78178", "price": "RON              326.58", "rank": "6", "department": "Home & Garden", "list_name": "Supreme Felted Dual Surface Rug Pad (8' x 10')", "product_name": "Supreme Felted Dual Surface Rug Pad (8' x 10')"}
{"page_title": "Alexa 'My Soft and Plush' Shag Rug (8' x 10')", "url": "http://www.overstock.com/Home-Garden/Alexa-My-Soft-and-Plush-Shag-Rug-8-x-10/4265216/product.html?IID=prod4265216&sec_iid=78178", "price": "RON              1180.85", "rank": "7", "department": "Home & Garden", "list_name": "Alexa 'My Soft and Plush' Shag Rug (8' x 10')", "product_name": "Alexa 'My Soft and Plush' Shag Rug (8' x 10')"}
{"page_title": "Safavieh Cozy Solid Dark Grey Shag Rug", "url": "http://www.overstock.com/Home-Garden/Safavieh-Cozy-Solid-Dark-Grey-Shag-Rug/7322535/product.html?IID=prod7322535&sec_iid=78178", "price": "RON              301.47", "rank": "4", "department": "Home & Garden", "list_name": "Safavieh Cozy Solid Dark Grey Shag Rug", "product_name": "Safavieh Cozy Solid Dark Grey Shag Rug"}
{"page_title": "Hand-hooked Alexa Moroccan Trellis Wool Rug (5' x 8')", "url": "http://www.overstock.com/Home-Garden/Hand-hooked-Alexa-Moroccan-Trellis-Wool-Rug-5-x-8/5777732/product.html?IID=prod5777732&sec_iid=78178", "price": "RON              854.20", "rank": "5", "department": "Home & Garden", "list_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (5' x 8')", "product_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (5' x 8')"}
{"page_title": "Solid Insulated Thermal Blackout Panel Pair (63-inch)", "url": "http://www.overstock.com/Home-Garden/Solid-Insulated-Thermal-Blackout-Panel-Pair-63-inch/2946006/product.html?IID=prod2946006&sec_iid=78178", "price": "RON              276.35", "rank": "3", "department": "Home & Garden", "list_name": "Solid Insulated Thermal Blackout Panel Pair (63-inch)", "product_name": "Solid Insulated Thermal Blackout Panel Pair (63-inch)"}
{"page_title": "Grommet Top Thermal Insulated 84-inch Blackout Curtain Panel Pair", "url": "http://www.overstock.com/Home-Garden/Grommet-Top-Thermal-Insulated-84-inch-Blackout-Curtain-Panel-Pair/4359827/product.html?IID=prod4359827&sec_iid=78178", "price": "RON              326.58", "rank": "2", "department": "Home & Garden", "list_name": "Grommet Top Thermal Insulated 84-inch Blackout Curtain Panel Pair", "product_name": "Grommet Top Thermal Insulated 84-inch Blackout Curtain Panel Pair"}
{"page_title": "West Coast Jewelry Men's Brushed-and-polished Titanium Ring with Comfort-fit Band", "url": "http://www.overstock.com/Jewelry-Watches/West-Coast-Jewelry-Mens-Brushed-and-polished-Titanium-Ring-with-Comfort-fit-Band/4097266/product.html?IID=prod4097266&sec_iid=78178", "price": "RON              135.65", "rank": "11", "department": "Watches", "list_name": "West Coast Jewelry Men's Brushed-and-polished Titanium Ring with Comfort-fit Band", "product_name": "West Coast Jewelry Men's Brushed-and-polished Titanium Ring with Comfort-fit Band"}
{"page_title": "Solid Insulated Thermal Blackout 84\" Curtain Panel Pair", "url": "http://www.overstock.com/Home-Garden/Solid-Insulated-Thermal-Blackout-84-Curtain-Panel-Pair/2946005/product.html?IID=prod2946005&sec_iid=78178", "price": "RON              336.19", "rank": "1", "department": "Home & Garden", "list_name": "Solid Insulated Thermal Blackout 84\" Curtain Panel Pair", "product_name": "Solid Insulated Thermal Blackout 84\" Curtain Panel Pair"}
{"page_title": "Miadora Sterling Silver Morganite and Diamond Ring", "url": "http://www.overstock.com/Jewelry-Watches/Miadora-Sterling-Silver-Morganite-and-Diamond-Ring/7617843/product.html?IID=prod7617843&sec_iid=78178", "price": "RON              487.38", "rank": "10", "department": "Watches", "list_name": "Miadora Sterling Silver Morganite and Diamond Ring", "product_name": "Miadora Sterling Silver Morganite and Diamond Ring"}
{"page_title": "Men's Tungsten Carbide Wood Inlay Band (8 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Mens-Tungsten-Carbide-Wood-Inlay-Band-8-mm/6364669/product.html?IID=prod6364669&sec_iid=78178", "price": "RON              271.30", "rank": "12", "department": "Watches", "list_name": "Men's Tungsten Carbide Wood Inlay Band (8 mm)", "product_name": "Men's Tungsten Carbide Wood Inlay Band (8 mm)"}
{"page_title": "Tressa Collection Sterling Silver Vintage Art Deco CZ Bridal & Engagement Ring", "url": "http://www.overstock.com/Jewelry-Watches/Tressa-Collection-Sterling-Silver-Vintage-Art-Deco-CZ-Bridal-Engagement-Ring/2869562/product.html?IID=prod2869562&sec_iid=78178", "price": "RON              150.70", "rank": "9", "department": "Watches", "list_name": "Tressa Collection Sterling Silver Vintage Art Deco CZ Bridal & Engagement Ring", "product_name": "Tressa Collection Sterling Silver Vintage Art Deco CZ Bridal & Engagement Ring"}
{"page_title": "Miadora Round-cut Diamond Accent High-polish Sterling Silver Ring", "url": "http://www.overstock.com/Jewelry-Watches/Miadora-Round-cut-Diamond-Accent-High-polish-Sterling-Silver-Ring/6690956/product.html?IID=prod6690956&sec_iid=78178", "price": "RON              226.08", "rank": "8", "department": "Watches", "list_name": "Miadora Round-cut Diamond Accent High-polish Sterling Silver Ring", "product_name": "Miadora Round-cut Diamond Accent High-polish Sterling Silver Ring"}
{"page_title": "Jewelry Armoire Over the Door Mirror Cabinet", "url": "http://www.overstock.com/Home-Garden/Jewelry-Armoire-Over-the-Door-Mirror-Cabinet/3538864/product.html?IID=prod3538864&sec_iid=78178", "price": "RON              653.20", "rank": "5", "department": "Watches", "list_name": "Jewelry Armoire Over the Door Mirror Cabinet", "product_name": "Jewelry Armoire Over the Door Mirror Cabinet"}
{"page_title": "Ultimate CZ Platinum over Silver Cubic Zirconia Wedding Ring Set", "url": "http://www.overstock.com/Jewelry-Watches/Ultimate-CZ-Platinum-over-Silver-Cubic-Zirconia-Wedding-Ring-Set/5318505/product.html?IID=prod5318505&sec_iid=78178", "price": "RON              472.30", "rank": "7", "department": "Watches", "list_name": "Ultimate CZ Platinum over Silver Cubic Zirconia Wedding Ring Set", "product_name": "Ultimate CZ Platinum over Silver Cubic Zirconia Wedding Ring Set"}
{"page_title": "Men's Tungsten with Black and Blue Carbon Fiber Inlay Ring (8 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Mens-Tungsten-with-Black-and-Blue-Carbon-Fiber-Inlay-Ring-8-mm/5162780/product.html?IID=prod5162780&sec_iid=78178", "price": "RON              205.98", "rank": "6", "department": "Watches", "list_name": "Men's Tungsten with Black and Blue Carbon Fiber Inlay Ring (8 mm)", "product_name": "Men's Tungsten with Black and Blue Carbon Fiber Inlay Ring (8 mm)"}
{"page_title": "Men's Black-plated Tungsten Carbide Comfort Fit Band (8 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Mens-Black-plated-Tungsten-Carbide-Comfort-Fit-Band-8-mm/4747377/product.html?IID=prod4747377&sec_iid=78178", "price": "RON              190.90", "rank": "4", "department": "Watches", "list_name": "Men's Black-plated Tungsten Carbide Comfort Fit Band (8 mm)", "product_name": "Men's Black-plated Tungsten Carbide Comfort Fit Band (8 mm)"}
{"page_title": "Men's Tungsten Carbide Brushed and Polished Beveled Edge Ring (7 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Mens-Tungsten-Carbide-Brushed-and-Polished-Beveled-Edge-Ring-7-mm/5085667/product.html?IID=prod5085667&sec_iid=78178", "price": "RON              185.85", "rank": "1", "department": "Watches", "list_name": "Men's Tungsten Carbide Brushed and Polished Beveled Edge Ring (7 mm)", "product_name": "Men's Tungsten Carbide Brushed and Polished Beveled Edge Ring (7 mm)"}
{"page_title": "Handmade One-inch Sterling Silver Filigree Raindrop Earrings (China)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Handmade-One-inch-Sterling-Silver-Filigree-Raindrop-Earrings-China/4798411/product.html?IID=prod4798411&sec_iid=78178", "price": "RON              90.40", "rank": "12", "department": "Worldstock", "list_name": "Handmade One-inch Sterling Silver Filigree Raindrop Earrings (China)", "product_name": "Handmade One-inch Sterling Silver Filigree Raindrop Earrings (China)"}
{"page_title": "Stainless-steel Lava LED Bracelet Watch with Digital Display", "url": "http://www.overstock.com/Jewelry-Watches/Stainless-steel-Lava-LED-Bracelet-Watch-with-Digital-Display/6204456/product.html?IID=prod6204456&sec_iid=78178", "price": "RON              54.25", "rank": "3", "department": "Watches", "list_name": "Stainless-steel Lava LED Bracelet Watch with Digital Display", "product_name": "Stainless-steel Lava LED Bracelet Watch with Digital Display"}
{"page_title": "Tungsten Carbide Men's Black Brushed Textured Center Ring (8 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Tungsten-Carbide-Mens-Black-Brushed-Textured-Center-Ring-8-mm/6484281/product.html?IID=prod6484281&sec_iid=78178", "price": "RON              281.37", "rank": "2", "department": "Watches", "list_name": "Tungsten Carbide Men's Black Brushed Textured Center Ring (8 mm)", "product_name": "Tungsten Carbide Men's Black Brushed Textured Center Ring (8 mm)"}
{"page_title": "Memory Wire 'Sakura Flower' Pearl and Mother of Pearl Choker (Thailand)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Memory-Wire-Sakura-Flower-Pearl-and-Mother-of-Pearl-Choker-Thailand/5096736/product.html?IID=prod5096736&sec_iid=78178", "price": "RON              195.95", "rank": "9", "department": "Worldstock", "list_name": "Memory Wire 'Sakura Flower' Pearl and Mother of Pearl Choker (Thailand)", "product_name": "Memory Wire 'Sakura Flower' Pearl and Mother of Pearl Choker (Thailand)"}
{"page_title": "Metal 'Tree of Life' Oil Drum Art (Haiti)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Metal-Tree-of-Life-Oil-Drum-Art-Haiti/3471069/product.html?IID=prod3471069&sec_iid=78178", "price": "RON              401.97", "rank": "11", "department": "Worldstock", "list_name": "Metal 'Tree of Life' Oil Drum Art (Haiti)", "product_name": "Metal 'Tree of Life' Oil Drum Art (Haiti)"}
{"page_title": "Double Face Sioux Floor Lamp (Colombia)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Double-Face-Sioux-Floor-Lamp-Colombia/1559502/product.html?IID=prod1559502&sec_iid=78178", "price": "RON              829.08", "rank": "10", "department": "Worldstock", "list_name": "Double Face Sioux Floor Lamp (Colombia)", "product_name": "Double Face Sioux Floor Lamp (Colombia)"}
{"page_title": "Mens 'Unity' Bracelet (Indonesia)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Mens-Unity-Bracelet-Indonesia/2678128/product.html?IID=prod2678128&sec_iid=78178", "price": "RON              728.58", "rank": "8", "department": "Worldstock", "list_name": "Mens 'Unity' Bracelet (Indonesia)", "product_name": "Mens 'Unity' Bracelet (Indonesia)"}
{"page_title": "Reclaimed Teak Wood and Steel Bench (India)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Reclaimed-Teak-Wood-and-Steel-Bench-India/5967720/product.html?IID=prod5967720&sec_iid=78178", "price": "RON              2020.01", "rank": "7", "department": "Worldstock", "list_name": "Reclaimed Teak Wood and Steel Bench (India)", "product_name": "Reclaimed Teak Wood and Steel Bench (India)"}
{"page_title": "Silverplated Multicolored Bead Bracelet (Kenya)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Silverplated-Multicolored-Bead-Bracelet-Kenya/5788182/product.html?IID=prod5788182&sec_iid=78178", "price": "RON              107.97", "rank": "4", "department": "Worldstock", "list_name": "Silverplated Multicolored Bead Bracelet (Kenya)", "product_name": "Silverplated Multicolored Bead Bracelet (Kenya)"}
{"page_title": "Wood Rush Grass Storage Box (China)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Wood-Rush-Grass-Storage-Box-China/6483836/product.html?IID=prod6483836&sec_iid=78178", "price": "RON              442.20", "rank": "5", "department": "Worldstock", "list_name": "Wood Rush Grass Storage Box (China)", "product_name": "Wood Rush Grass Storage Box (China) "}
{"page_title": "12 inches Square x 20-inch Wooden Hand-carved Walnut Oil Twist Stool (Thailand)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/12-inches-Square-x-20-inch-Wooden-Hand-carved-Walnut-Oil-Twist-Stool-Thailand/5221190/product.html?IID=prod5221190&sec_iid=78178", "price": "RON              904.47", "rank": "6", "department": "Worldstock", "list_name": "12 inches Square x 20-inch Wooden Hand-carved Walnut Oil Twist Stool (Thailand)", "product_name": "12 inches Square x 20-inch Wooden Hand-carved Walnut Oil Twist Stool (Thailand)"}
{"page_title": "Alpaca Silver Gemstone Teardrop Earrings (Mexico)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Alpaca-Silver-Gemstone-Teardrop-Earrings-Mexico/5754286/product.html?IID=prod5754286&sec_iid=78178", "price": "RON              110.50", "rank": "3", "department": "Worldstock", "list_name": "Alpaca Silver Gemstone Teardrop Earrings (Mexico)", "product_name": "Alpaca Silver Gemstone Teardrop Earrings (Mexico) "}
{"page_title": "Solid Sarong (Indonesia)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Solid-Sarong-Indonesia/4155328/product.html?IID=prod4155328&sec_iid=78178", "price": "RON              65.28", "rank": "2", "department": "Worldstock", "list_name": "Solid Sarong (Indonesia)", "product_name": "Solid Sarong (Indonesia)"}
{"page_title": "Handmade Rosewood Nightstand with Forged-iron Hardware (India)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Handmade-Rosewood-Nightstand-with-Forged-iron-Hardware-India/2002421/product.html?IID=prod2002421&sec_iid=78178", "price": "RON              949.69", "rank": "1", "department": "Worldstock", "list_name": "Handmade Rosewood Nightstand with Forged-iron Hardware (India)", "product_name": "Handmade Rosewood Nightstand with Forged-iron Hardware (India)"}
{"page_title": "Cirque Du Soleil: Baroque Odyssey (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Cirque-Du-Soleil-Baroque-Odyssey-DVD/88837/product.html?IID=prod88837&sec_iid=78178", "price": "RON              79.80", "rank": "12", "department": "Entertainment", "list_name": "Cirque Du Soleil: Baroque Odyssey (DVD)", "product_name": "Cirque Du Soleil: Baroque Odyssey (DVD)"}
{"page_title": "A Fine Romance: Falling in Love With the English Countryside (Hardcover)", "url": "http://www.overstock.com/Books-Movies-Music-Games/A-Fine-Romance-Falling-in-Love-With-the-English-Countryside-Hardcover/8120754/product.html?IID=prod8120754&sec_iid=78178", "price": "RON              103.49", "rank": "9", "department": "Entertainment", "list_name": "A Fine Romance: Falling in Love With the English Countryside (Hardcover)", "product_name": "A Fine Romance: Falling in Love With the English Countryside (Hardcover)"}
{"page_title": "Brown Sugar (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Brown-Sugar-DVD/158578/product.html?IID=prod158578&sec_iid=78178", "price": "RON              38.74", "rank": "8", "department": "Entertainment", "list_name": "Brown Sugar (DVD)", "product_name": "Brown Sugar (DVD)"}
{"page_title": "Yo-Yo: Tricks and Tips", "url": "http://www.overstock.com/Books-Movies-Music-Games/Yo-Yo-Tricks-and-Tips/7303023/product.html?IID=prod7303023&sec_iid=78178", "price": "RON              48.74", "rank": "10", "department": "Entertainment", "list_name": "Yo-Yo: Tricks and Tips", "product_name": "Yo-Yo: Tricks and Tips"}
{"page_title": "When You Are Engulfed in Flames (Paperback)", "url": "http://www.overstock.com/Books-Movies-Music-Games/When-You-Are-Engulfed-in-Flames-Paperback/3642769/product.html?IID=prod3642769&sec_iid=78178", "price": "RON              61.40", "rank": "11", "department": "Entertainment", "list_name": "When You Are Engulfed in Flames (Paperback)", "product_name": "When You Are Engulfed in Flames (Paperback)"}
{"page_title": "Sanctuary: The Complete First Season (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Sanctuary-The-Complete-First-Season-DVD/4073586/product.html?IID=prod4073586&sec_iid=78178", "price": "RON              97.41", "rank": "7", "department": "Entertainment", "list_name": "Sanctuary: The Complete First Season (DVD)", "product_name": "Sanctuary: The Complete First Season (DVD)"}
{"page_title": "Jolly Jumble: Jumble Puzzles to Keep You in High Spirits! (Paperback)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Jolly-Jumble-Jumble-Puzzles-to-Keep-You-in-High-Spirits-Paperback/3375377/product.html?IID=prod3375377&sec_iid=78178", "price": "RON              44.58", "rank": "6", "department": "Entertainment", "list_name": "Jolly Jumble: Jumble Puzzles to Keep You in High Spirits! (Paperback)", "product_name": "Jolly Jumble: Jumble Puzzles to Keep You in High Spirits! (Paperback)"}
{"page_title": "PS3 - DualShock 3 Controller Black", "url": "http://www.overstock.com/Books-Movies-Music-Games/PS3-DualShock-3-Controller-Black/6152728/product.html?IID=prod6152728&sec_iid=78178", "price": "RON              212.21", "rank": "5", "department": "Entertainment", "list_name": "PS3 - DualShock 3 Controller Black", "product_name": "PS3 - DualShock 3 Controller Black"}
{"page_title": "You Can Heal Your Life (DVD video)", "url": "http://www.overstock.com/Books-Movies-Music-Games/You-Can-Heal-Your-Life-DVD-video/2750857/product.html?IID=prod2750857&sec_iid=78178", "price": "RON              80.40", "rank": "3", "department": "Entertainment", "list_name": "You Can Heal Your Life (DVD video)", "product_name": "You Can Heal Your Life (DVD video)"}
{"page_title": "The Outer Limits: The Original Series: Season 1 Vol. 2 (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/The-Outer-Limits-The-Original-Series-Season-1-Vol.-2-DVD/2523911/product.html?IID=prod2523911&sec_iid=78178", "price": "RON              114.91", "rank": "1", "department": "Entertainment", "list_name": "The Outer Limits: The Original Series: Season 1 Vol. 2 (DVD)", "product_name": "The Outer Limits: The Original Series: Season 1 Vol. 2 (DVD)"}
{"page_title": "Valley Girl (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Valley-Girl-DVD/474610/product.html?IID=prod474610&sec_iid=78178", "price": "RON              40.20", "rank": "4", "department": "Entertainment", "list_name": "Valley Girl (DVD)", "product_name": "Valley Girl (DVD)"}
{"page_title": "True Crime Stories: Cases That Shocked America (Hardcover)", "url": "http://www.overstock.com/Books-Movies-Music-Games/True-Crime-Stories-Cases-That-Shocked-America-Hardcover/6640168/product.html?IID=prod6640168&sec_iid=78178", "price": "RON              116.65", "rank": "2", "department": "Entertainment", "list_name": "True Crime Stories: Cases That Shocked America (Hardcover)", "product_name": "True Crime Stories: Cases That Shocked America (Hardcover)"}
{"page_title": "Ray-Ban Unisex Tortoise Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-Unisex-Tortoise-Sunglasses/8028460/product.html?IID=prod8028460&sec_iid=78178", "price": "RON              502.47", "rank": "12", "department": "Clothing", "list_name": "Ray-Ban Unisex Tortoise Sunglasses", "product_name": "Ray-Ban Unisex Tortoise Sunglasses"}
{"page_title": "R & M Richards Women's Lace Accented Empire Dress", "url": "http://www.overstock.com/Clothing-Shoes/R-M-Richards-Womens-Lace-Accented-Empire-Dress/7894704/product.html?IID=prod7894704&sec_iid=78178", "price": "RON              251.20", "rank": "11", "department": "Clothing", "list_name": "R & M Richards Women's Lace Accented Empire Dress", "product_name": "R & M Richards Women's Lace Accented Empire Dress"}
{"page_title": "London Fog Knightsbridge Tote Bag", "url": "http://www.overstock.com/Clothing-Shoes/London-Fog-Knightsbridge-Tote-Bag/6652205/product.html?IID=prod6652205&sec_iid=78178", "price": "RON              417.05", "rank": "10", "department": "Clothing", "list_name": "London Fog Knightsbridge Tote Bag", "product_name": "London Fog Knightsbridge Tote Bag"}
{"page_title": "Ray-Ban Unisex Original Wayfarer Black Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-Unisex-Original-Wayfarer-Black-Sunglasses/6168721/product.html?IID=prod6168721&sec_iid=78178", "price": "RON              552.70", "rank": "9", "department": "Clothing", "list_name": "Ray-Ban Unisex Original Wayfarer Black Sunglasses", "product_name": "Ray-Ban Unisex Original Wayfarer Black Sunglasses"}
{"page_title": "Ray-Ban Men's 'RB2132' New Wayfarer Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-Mens-RB2132-New-Wayfarer-Sunglasses/7031048/product.html?IID=prod7031048&sec_iid=78178", "price": "RON              502.47", "rank": "6", "department": "Clothing", "list_name": "Ray-Ban Men's 'RB2132' New Wayfarer Sunglasses", "product_name": "Ray-Ban Men's 'RB2132' New Wayfarer Sunglasses"}
{"page_title": "R & M Richards Women's 2-piece Mandarin Jacket Dress", "url": "http://www.overstock.com/Clothing-Shoes/R-M-Richards-Womens-2-piece-Mandarin-Jacket-Dress/8095811/product.html?IID=prod8095811&sec_iid=78178", "price": "RON              401.97", "rank": "7", "department": "Clothing", "list_name": "R & M Richards Women's 2-piece Mandarin Jacket Dress", "product_name": "R & M Richards Women's 2-piece Mandarin Jacket Dress"}
{"page_title": "R & M Richards Women's Cascading Ruffle Detail Dress", "url": "http://www.overstock.com/Clothing-Shoes/R-M-Richards-Womens-Cascading-Ruffle-Detail-Dress/7753098/product.html?IID=prod7753098&sec_iid=78178", "price": "RON              267.81", "rank": "2", "department": "Clothing", "list_name": "R & M Richards Women's Cascading Ruffle Detail Dress", "product_name": "R & M Richards Women's Cascading Ruffle Detail Dress"}
{"page_title": "24/7 Comfort Apparel Women's 3/4-sleeve Tunic", "url": "http://www.overstock.com/Clothing-Shoes/24-7-Comfort-Apparel-Womens-3-4-sleeve-Tunic/6115828/product.html?IID=prod6115828&sec_iid=78178", "price": "RON              150.70", "rank": "8", "department": "Clothing", "list_name": "24/7 Comfort Apparel Women's 3/4-sleeve Tunic", "product_name": "24/7 Comfort Apparel Women's 3/4-sleeve Tunic"}
