{"url": "http://www.staples.com/Apple/cat_SC1949", "text": "Apple\u00ae", "level": 1}
{"url": "http://www.staples.com/iPad-Accessories/cat_DP5151", "text": "iPad\u00ae Accessories", "level": 0, "parent_text": "Apple\u00ae", "parent_url": "http://www.staples.com/Apple/cat_SC1949"}
{"url": "http://www.staples.com/iPhone-Accessories/cat_DP8130", "text": "iPhone\u00ae Accessories", "level": 0, "parent_text": "Apple\u00ae", "parent_url": "http://www.staples.com/Apple/cat_SC1949"}
{"url": "http://www.staples.com/iPod-Accessories/cat_DP8131", "text": "iPod\u00ae Accessories", "level": 0, "parent_text": "Apple\u00ae", "parent_url": "http://www.staples.com/Apple/cat_SC1949"}
{"url": "http://www.staples.com/Mac-Accessories/cat_DP8132", "text": "Mac\u00ae Accessories", "level": 0, "parent_text": "Apple\u00ae", "parent_url": "http://www.staples.com/Apple/cat_SC1949"}
{"url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3", "text": "PCs | Drives | Accessories", "level": 1}
{"url": "http://www.staples.com/PCs-Laptops-Tablets/cat_CG71", "text": "PCs / Laptops / Tablets", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Monitors-Digital-Projectors/cat_CG4", "text": "Computer Monitors / Screen Filters", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Drives-Memory-Storage/cat_CG104", "text": "Hard Drives", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Networking-Cables/cat_CG58", "text": "Networking", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Computer-Components/cat_DP3943", "text": "Computer Components", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Flash-Memory-Cards-Readers/cat_CG1125", "text": "Flash Memory Cards & Readers", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682", "text": "Phones | Cameras | Electronics", "level": 1}
{"url": "http://www.staples.com/Cameras-Camcorders-Accessories/cat_CG43", "text": "Cameras / Camcorders / Accessories", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/E-Readers-Accessories/cat_DP2258", "text": "E-Readers / Accessories", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Bluetooth-Headsets/cat_CL163950", "text": "Bluetooth Headsets", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Telephones-Headsets-Cords/cat_CG14", "text": "Telephones / Headsets / Cords", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/GPS-Accessories/cat_CG59", "text": "GPS / Accessories", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Audio/cat_CG1265", "text": "Audio", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681", "text": "Printers | Shredders | Machines", "level": 1}
{"url": "http://www.staples.com/Printers-All-in-Ones/cat_CG44", "text": "Printers", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Copiers-Fax/cat_CG51", "text": "Copiers / Fax", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Scanners/cat_CL158948", "text": "Scanners", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Shredders-Oil-Bags/cat_CG1103", "text": "Shredders / Oil / Bags", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Document-Cameras/cat_CL169123", "text": "Document Cameras", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679", "text": "Envelopes | Labels | Mailing", "level": 1}
{"url": "http://www.staples.com/Labels/cat_CG24", "text": "Labels", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Inventory-Shipping-Tags/cat_CG2839", "text": "Tags", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Envelopes/cat_CG23", "text": "Envelopes", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Packaging-Tape-Shipping-Tape/cat_DP1427", "text": "Packaging Tape / Shipping Tape", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Mobile-Phones-Accessories/cat_SC5308", "text": "Mobile Phones | Accessories", "level": 1}
{"url": "http://www.staples.com/Mobile-Phones/cat_CG2859", "text": "Mobile Phones", "level": 0, "parent_text": "Mobile Phones | Accessories", "parent_url": "http://www.staples.com/Mobile-Phones-Accessories/cat_SC5308"}
{"url": "http://www.staples.com/Mobile-Phones-Accessories/cat_CG6", "text": "Mobile Phone Accessories", "level": 0, "parent_text": "Mobile Phones | Accessories", "parent_url": "http://www.staples.com/Mobile-Phones-Accessories/cat_SC5308"}
{"url": "http://www.staples.com/Bluetooth-Headsets/cat_CL163950", "text": "Bluetooth Headsets", "level": 0, "parent_text": "Mobile Phones | Accessories", "parent_url": "http://www.staples.com/Mobile-Phones-Accessories/cat_SC5308"}
{"url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786", "text": "TV | Home Entertainment", "level": 1}
{"url": "http://www.staples.com/TV-Home-Theater/cat_CG1402", "text": "TV & Home Theater", "level": 0, "parent_text": "TV | Home Entertainment", "parent_url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786"}
{"url": "http://www.staples.com/Audio/cat_CG1265", "text": "Audio", "level": 0, "parent_text": "TV | Home Entertainment", "parent_url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786"}
{"url": "http://www.staples.com/Home-Entertainment-Furniture/cat_CG1404", "text": "Home Entertainment Furniture", "level": 0, "parent_text": "TV | Home Entertainment", "parent_url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786"}
{"url": "http://www.staples.com/TV-Accessories/cat_DP5317", "text": "TV Accessories", "level": 0, "parent_text": "TV | Home Entertainment", "parent_url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786"}
{"url": "http://www.staples.com/Movies-TV-Shows/cat_CG1406", "text": "Movies & TV Shows", "level": 0, "parent_text": "TV | Home Entertainment", "parent_url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786"}
{"url": "http://www.staples.com/Gaming/cat_CG1403", "text": "Gaming", "level": 0, "parent_text": "TV | Home Entertainment", "parent_url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786"}
{"url": "http://www.staples.com/Software-Cloud-Software-Tech-Support/cat_SC1941", "text": "Software | Cloud Software | Tech Support", "level": 1}
{"url": "http://www.staples.com/Computer-Software/cat_CG5", "text": "Computer Software", "level": 0, "parent_text": "Software | Cloud Software | Tech Support", "parent_url": "http://www.staples.com/Software-Cloud-Software-Tech-Support/cat_SC1941"}
{"url": "http://www.staples.comhttps://appcenter.staples.com/home", "text": "Cloud Software", "level": 0, "parent_text": "Software | Cloud Software | Tech Support", "parent_url": "http://www.staples.com/Software-Cloud-Software-Tech-Support/cat_SC1941"}
{"url": "http://www.staples.com/CD-DVD-Blu-Ray-Burners-Media/cat_CG1039", "text": "CD / DVD / Blu-Ray Burners & Media", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Cables/cat_DP1426", "text": "Cables", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Headsets/cat_CG1215", "text": "Headsets", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Mice-Keyboards-Speakers/cat_CG18", "text": "Mice / Keyboards / Speakers", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Batteries-Power/cat_CG75", "text": "Batteries & Power", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Projectors-Screens-Pointers/cat_DP1446", "text": "Projectors / Screens / Pointers", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Livescribe-Smartpens-Accessories/cat_CG1271", "text": "Livescribe Smartpens / Accessories", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Portable-DVD-TV-Radio/cat_CG1268", "text": "Portable:  DVD / TV / Radio", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Electronic-Translator-Dictionary/cat_CG2895", "text": "Electronic Translator / Dictionary", "level": 0, "parent_text": "Phones | Cameras | Electronics", "parent_url": "http://www.staples.com/Phones-Cameras-Electronics/cat_SC1682"}
{"url": "http://www.staples.com/Scanner-Accessories/cat_CL168162", "text": "Scanner Accessories", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Laminators-Pouches-Sheets/cat_DP2148", "text": "Laminators / Pouches / Sheets", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Projectors-Screens-Pointers/cat_DP1446", "text": "Projectors / Screens / Pointers", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Audio-Tapes-Cassettes/cat_CL140560", "text": "Audio Tapes & Cassettes", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Binding-Machines-Spines-Covers/cat_DP1301", "text": "Binding Machines / Spines / Covers", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Shipping-Boxes/cat_CG1274", "text": "Shipping Boxes", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Bubble-Wrap-Void-Fill-Materials/cat_DP1784", "text": "Bubble Wrap / Void Fill Materials", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.comhttp://www.staples.com/Beats-by-Dre-Headphones/cat_CL210844", "text": "Beats By Dre", "level": 0, "parent_text": "TV | Home Entertainment", "parent_url": "http://www.staples.com/TV-Home-Entertainment/cat_SC1786"}
{"url": "http://www.staples.comhttp://www.staples.com/sbd/cre/programs/serviceplans/index.html", "text": "Staples Protection Plans", "level": 0, "parent_text": "Software | Cloud Software | Tech Support", "parent_url": "http://www.staples.com/Software-Cloud-Software-Tech-Support/cat_SC1941"}
{"url": "http://www.staples.comhttp://www.staples.com/sbd/cre/tech-services/get-help-now/", "text": "Tech Support Services", "level": 0, "parent_text": "Software | Cloud Software | Tech Support", "parent_url": "http://www.staples.com/Software-Cloud-Software-Tech-Support/cat_SC1941"}
{"url": "http://www.staples.com/Computer-Accessories/cat_CG1086", "text": "Computer Accessories", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.comhttps://appcenter.staples.com/home?CID=DotcomPCSuperCategory", "text": "Cloud Software", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Computer-Memory/cat_DP1986", "text": "Computer Memory", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Computer-Stands-Carts/cat_DP1570", "text": "Computer Stands / Carts", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/Calculators/cat_DP900", "text": "Calculators", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Label-Makers-Printers-Tapes-Labels/cat_DP904", "text": "Label Makers / Printers / Tapes / Labels", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Typewriters/cat_DP908", "text": "Typewriters", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Time-Clocks-Time-Recorders/cat_DP3901", "text": "Time Clocks / Time Recorders", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Digital-Voice-Recorders/cat_CL140515", "text": "Digital / Voice Recorders", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Handheld-Terminals/cat_CL167347", "text": "Handheld Terminals", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/PA-Systems-Lecterns-Microphones/cat_CG1317", "text": "PA Systems / Lecterns / Microphones", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Mailers-Tubes/cat_DP1781", "text": "Mailers / Tubes", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Stretch-Wrap-Strapping-Supplies/cat_DP1808", "text": "Stretch Wrap / Strapping Supplies", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Poly-Bags/cat_DP1858", "text": "Poly Bags", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Mailroom-Equipment-Supplies/cat_DP1460", "text": "Mailroom Equipment / Supplies", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Label-Makers-Printers-Tapes-Labels/cat_DP904", "text": "Label Makers / Printers / Tapes / Labels", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Laptop-Bags-Luggage-School-Uniforms/cat_CG20", "text": "Laptop Bags / Luggage / School Uniforms", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/USB-Flash-Drives/cat_CL142211", "text": "USB Flash Drives", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.comhttp://www.staples.com/Laptops/cat_CL167289", "text": "laptops", "level": 0, "parent_text": "PCs | Drives | Accessories", "parent_url": "http://www.staples.com/PCs-Drives-Accessories/cat_SC3"}
{"url": "http://www.staples.com/The-Neat-Company-Scanners-Staples/cat_CL208624", "text": "The Neat Company Scanners \u2013 Staples", "level": 0, "parent_text": "Printers | Shredders | Machines", "parent_url": "http://www.staples.com/Printers-Shredders-Machines/cat_SC1681"}
{"url": "http://www.staples.com/Postal-Scales-Letter-Folders/cat_CG1281", "text": "Postal Scales / Letter Folders", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Recycled-Mailing-Supplies/cat_DP2216", "text": "Recycled Mailing Supplies", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Letter-Opening-Magnifiers/cat_CG1287", "text": "Letter Opening / Magnifiers", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Scotch-Re-Use-Shipping-Supplies/cat_CL168118", "text": "Scotch\u00ae Re-Use Shipping Supplies", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Custom-Marketing-Materials/cat_CL167719", "text": "Custom Marketing Materials", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Name-Badges-Holders/cat_DP1520", "text": "ID Badges & Holders", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Stationery-Invitations/cat_DP1422", "text": "Stationery / Invitations", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.comhttp://www.staples.com/sbd/cre/products/martha-stewart-home-office/labels_tags_bands.html", "text": "Martha Stewart Home Office Labels", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.comhttp://www.staples.com/Envelopes/cat_CG23", "text": "sized envelopes", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.comhttp://www.staples.com/Labels/cat_CG24", "text": "labels", "level": 0, "parent_text": "Envelopes | Labels | Mailing", "parent_url": "http://www.staples.com/Envelopes-Labels-Mailing/cat_SC1679"}
{"url": "http://www.staples.com/Office-Supplies/cat_SC1", "text": "Office Supplies", "level": 1}
{"url": "http://www.staples.com/Paper/cat_CG10", "text": "Paper", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/File-Folders-Jackets-Pockets/cat_CG15", "text": "File Folders / Jackets / Pockets", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Notebooks-Notepads/cat_CG1234", "text": "Notebooks / Notepads", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Tape-Glue-Adhesives/cat_DP100", "text": "Tape / Glue / Adhesives", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Pens-Pencils-Markers/cat_CG11", "text": "Pens / Pencils / Markers", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Envelopes/cat_CG23", "text": "Envelopes", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Dividers-Tabs-Fasteners-Inserts/cat_CG1262", "text": "Dividers / Tabs / Fasteners / Inserts", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Gifts-Gift-Cards/cat_SC1699", "text": "Gifts | Gift Cards", "level": 1}
{"url": "http://www.staples.com/Gift-Cards/cat_CL166326", "text": "Gift Cards", "level": 0, "parent_text": "Gifts | Gift Cards", "parent_url": "http://www.staples.com/Gifts-Gift-Cards/cat_SC1699"}
{"url": "http://www.staples.com/E-Gift-Cards/cat_CL168827", "text": "E-Gift Cards", "level": 0, "parent_text": "Gifts | Gift Cards", "parent_url": "http://www.staples.com/Gifts-Gift-Cards/cat_SC1699"}
{"url": "http://www.staples.com/Gifts-Games-Accessories/cat_DP5203", "text": "Gifts, Games & Accessories", "level": 0, "parent_text": "Gifts | Gift Cards", "parent_url": "http://www.staples.com/Gifts-Gift-Cards/cat_SC1699"}
{"url": "http://www.staples.com/Custom-Photo-Gifts/cat_CL168343", "text": "Custom Photo Gifts", "level": 0, "parent_text": "Gifts | Gift Cards", "parent_url": "http://www.staples.com/Gifts-Gift-Cards/cat_SC1699"}
{"url": "http://www.staples.com/Edible-Gifts-Desserts/cat_CG1252", "text": "Edible Gifts / Desserts", "level": 0, "parent_text": "Gifts | Gift Cards", "parent_url": "http://www.staples.com/Gifts-Gift-Cards/cat_SC1699"}
{"url": "http://www.staples.com/Sports-Memorabilia-Gifts/cat_DP8169", "text": "Sports Memorabilia & Gifts", "level": 0, "parent_text": "Gifts | Gift Cards", "parent_url": "http://www.staples.com/Gifts-Gift-Cards/cat_SC1699"}
{"url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686", "text": "Teaching | Drafting | Art", "level": 1}
{"url": "http://www.staples.com/Drawing-Arts-Crafts/cat_CG821", "text": "Drawing / Arts / Crafts", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Design-Drafting/cat_DP4141", "text": "Design / Drafting", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Erase-Presentation-Boards-Chalkboards/cat_CG1304", "text": "Erase & Presentation Boards / Chalkboards", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Teaching-Learning-Resources/cat_CG1300", "text": "Teaching & Learning Resources", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Flags-Maps-Magnifiers/cat_CG1302", "text": "Flags / Maps / Magnifiers", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Laminators-Pouches-Sheets/cat_DP2148", "text": "Laminators / Pouches / Sheets", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101", "text": "Boards | Easels | Dry-Erase", "level": 1}
{"url": "http://www.staples.com/Dry-Erase-Boards-Markers-Cleaners/cat_DP2078", "text": "Dry-Erase/ Boards / Markers / Cleaners", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Presentation-Boards/cat_CL140934", "text": "Presentation Boards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Bulletin-Boards/cat_DP2075", "text": "Bulletin Boards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Foam-Boards/cat_CL140933", "text": "Foam Boards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Calendars-Planners/cat_CG12", "text": "Calendars | Planners", "level": 1}
{"url": "http://www.staples.com/Planners/cat_CL166388", "text": "Planners", "level": 0, "parent_text": "Calendars | Planners", "parent_url": "http://www.staples.com/Calendars-Planners/cat_CG12"}
{"url": "http://www.staples.com/Desk-Calendars/cat_CL166095", "text": "Desk Calendars", "level": 0, "parent_text": "Calendars | Planners", "parent_url": "http://www.staples.com/Calendars-Planners/cat_CG12"}
{"url": "http://www.staples.com/Journals-Diaries/cat_CL166390", "text": "Journals / Diaries", "level": 0, "parent_text": "Calendars | Planners", "parent_url": "http://www.staples.com/Calendars-Planners/cat_CG12"}
{"url": "http://www.staples.com/Wall-Calendars/cat_CL166389", "text": "Wall Calendars", "level": 0, "parent_text": "Calendars | Planners", "parent_url": "http://www.staples.com/Calendars-Planners/cat_CG12"}
{"url": "http://www.staples.com/Personal-Organizers-Refills/cat_CL166401", "text": "Personal Organizers & Refills", "level": 0, "parent_text": "Calendars | Planners", "parent_url": "http://www.staples.com/Calendars-Planners/cat_CG12"}
{"url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2", "text": "Furniture | Chairs | Cabinets", "level": 1}
{"url": "http://www.staples.com/Chairs/cat_CG32", "text": "Chairs", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Desks/cat_CG33", "text": "Desks", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Furniture-Collections/cat_CG97", "text": "Furniture Collections", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/File-Cabinets/cat_CG34", "text": "File Cabinets", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Chair-Mats-Floormats-Rugs/cat_CG93", "text": "Chair Mats / Floormats / Rugs", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.comhttp://www.staples.com/sbd/cre/products/martha-stewart-home-office/index.html", "text": "Martha Stewart Home Office", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Post-it-Stickies-Notes-Flags/cat_DP4736", "text": "Post-it\u00ae / Stickies\u2122 Notes & Flags", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Clips-Tacks-Rubber-Bands/cat_CG1036", "text": "Clips / Tacks / Rubber Bands", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Planners/cat_CL166388", "text": "Planners", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Binding-Machines-Spines-Covers/cat_DP1301", "text": "Binding Machines / Spines / Covers", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Scrapbooking/cat_DP4579", "text": "Scrapbooking", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Label-Makers-Printers-Tapes-Labels/cat_DP904", "text": "Label Makers / Printers / Tapes / Labels", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Easels-Easel-Pads/cat_DP2195", "text": "Easels / Easel Pads", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Custom-Calendars/cat_CL167730", "text": "Custom Calendars", "level": 0, "parent_text": "Calendars | Planners", "parent_url": "http://www.staples.com/Calendars-Planners/cat_CG12"}
{"url": "http://www.staples.com/Panel-Cubicle-Systems/cat_CG37", "text": "Panel / Cubicle Systems", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Bookcases/cat_CG31", "text": "Bookcases", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Tables/cat_CG39", "text": "Tables", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Carts-Stands/cat_CG94", "text": "Carts / Stands", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Calculators/cat_DP900", "text": "Calculators", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Desk-Calendars/cat_CL166095", "text": "Desk Calendars", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Journals-Diaries/cat_CL166390", "text": "Journals / Diaries", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Wall-Calendars/cat_CL166389", "text": "Wall Calendars", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Pantone/cat_DP4414", "text": "Pantone\u00ae", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Custom-Photo-Books/cat_CL167732", "text": "Custom Photo Books", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Games-Toys-Crafts/cat_CG2853", "text": "Games / Toys / Crafts", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Poster-Boards/cat_CL140932", "text": "Poster Boards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Specialty-Boards/cat_DP4978", "text": "Specialty Boards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Magnets-Pins-Tacks/cat_DP2079", "text": "Magnets / Pins / Tacks", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Clipboards/cat_CL140606", "text": "Clipboards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Storage-Cubes-Cabinets/cat_DP1492", "text": "Storage Cubes / Cabinets", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Sorters-Storage-Shelving/cat_CG40", "text": "Sorters / Storage / Shelving", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Lamps/cat_CG35", "text": "Lamps", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Safes-Fire-Chests/cat_CG1022", "text": "Safes / Fire Chests", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Personal-Organizers-Refills/cat_CL166401", "text": "Personal Organizers & Refills", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Storage-Boxes-Bins-Cabinets/cat_CG1077", "text": "Storage / Boxes / Bins / Cabinets", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Binders-Pocket-Folders-Report-Covers/cat_CG2860", "text": "Binders / Pocket Folders / Report Covers", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/School-Uniforms/cat_DP8386", "text": "School Uniforms", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.comhttp://www.staples.com/Backpacks/cat_CL142745http://www.staples.com/Backpacks/cat_DP3983", "text": "best backpacks for kids, travel", "level": 0, "parent_text": "Teaching | Drafting | Art", "parent_url": "http://www.staples.com/Teaching-Drafting-Art/cat_SC1686"}
{"url": "http://www.staples.com/Markers-Accessories/cat_DP4973", "text": "Markers / Accessories", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Message-Boards/cat_DP2084", "text": "Message Boards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Calendar-Boards/cat_CL142105", "text": "Calendar Boards", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Chalkboards-Chalk/cat_CL130202", "text": "Chalkboards / Chalk", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Martha-Stewart-Wall-Manager/cat_DP8322", "text": "Martha Stewart Wall Manager", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Decor-Art-Accents-Frames/cat_CG853", "text": "Decor / Art / Accents / Frames", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Clocks-Thermometers/cat_CG1319", "text": "Clocks/Thermometers", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Hangers-Hooks-Mounts/cat_CG36", "text": "Hangers / Hooks / Mounts", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Trash-Cans-Recycling-Bins/cat_CG1321", "text": "Trash Cans / Recycling Bins", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Heating-Cooling-Air-Quality/cat_DP4952", "text": "Heating / Cooling / Air Quality", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Flooring/cat_DP8405", "text": "Flooring", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Custom-Calendars/cat_CL167730", "text": "Custom Calendars", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Desk-Organizers/cat_CG30", "text": "Desk Organizers", "level": 0, "parent_text": "Office Supplies", "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.com/Pink-Ribbon-Products/cat_CG1089", "parent_text": "Office Supplies", "level": 0, "parent_url": "http://www.staples.com/Office-Supplies/cat_SC1"}
{"url": "http://www.staples.comhttp://www.staples.com/Office-Supplies/cat_SC1", "text": "office products", "level": 0, "parent_text": "Boards | Easels | Dry-Erase", "parent_url": "http://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101"}
{"url": "http://www.staples.com/Furniture-Polish-Cleaners/cat_CL142820", "text": "Furniture Polish & Cleaners", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Garden-Patio/cat_CG2801", "text": "Garden & Patio", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.comhttp://www.staples.com/Office-Chairs/cat_DP4972", "text": "office chairs", "level": 0, "parent_text": "Furniture | Chairs | Cabinets", "parent_url": "http://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2"}
{"url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677", "text": "Filing | Binders | Organizers", "level": 1}
{"url": "http://www.staples.com/Binders-Pocket-Folders-Report-Covers/cat_CG2860", "text": "Binders / Pocket Folders / Report Covers", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/File-Folders-Jackets-Pockets/cat_CG15", "text": "File Folders / Jackets / Pockets", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Storage-Boxes-Bins-Cabinets/cat_CG1077", "text": "Storage / Boxes / Bins / Cabinets", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Desk-Organizers/cat_CG30", "text": "Desk Organizers", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Dividers-Tabs-Fasteners-Inserts/cat_CG1262", "text": "Dividers / Tabs / Fasteners / Inserts", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Laminators-Pouches-Sheets/cat_DP2148", "text": "Laminators / Pouches / Sheets", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Binding-Machines-Spines-Covers/cat_DP1301", "text": "Binding Machines / Spines / Covers", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Sorters-Storage-Shelving/cat_CG40", "text": "Sorters / Storage / Shelving", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Index-Card-Index-Card-Storage/cat_DP2227", "text": "Index Card / Index Card Storage", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Label-Makers-Printers-Tapes-Labels/cat_DP904", "text": "Label Makers / Printers / Tapes / Labels", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678", "text": "Pens | Tape | Desk Supplies", "level": 1}
{"url": "http://www.staples.com/Pens-Pencils-Markers/cat_CG11", "text": "Pens / Pencils / Markers", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.comhttp://www.staples.com/Poppin-Office-Supplies/cat_CG2907", "text": "Poppin Office Products", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Tape-Glue-Adhesives/cat_DP100", "text": "Tape / Glue / Adhesives", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Staplers-Staples-Removers/cat_CG1417", "text": "Staplers / Staples / Removers", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Trimmers-Punches-Scissors/cat_CG1249", "text": "Trimmers / Punches / Scissors", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Correction-Erasers/cat_CG1246", "text": "Correction / Erasers", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684", "text": "Coffee | Water | Snacks", "level": 1}
{"url": "http://www.staples.com/Beverages/cat_CG1251", "text": "Beverages", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Coffee-Coffee-Makers-Sugar/cat_DP4533", "text": "Coffee / Coffee Makers / Sugar", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676", "text": "Paper | Notebooks | Post-its", "level": 1}
{"url": "http://www.staples.com/Paper/cat_CG10", "text": "Paper", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Notebooks-Notepads/cat_CG1234", "text": "Notebooks / Notepads", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Business-Cards-Printable/cat_CL141306", "text": "Business Cards Printable", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683", "text": "Cleaning | Facilities | Tools", "level": 1}
{"url": "http://www.staples.com/Paper-Towels-Tissues-Napkins/cat_DP1865", "text": "Paper Towels / Tissues / Napkins", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Cleaners-Chemicals-Soaps-Wipes/cat_CG1238", "text": "Cleaners: Chemicals / Soaps / Wipes", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Cleaning-Supplies-Equipment/cat_DP8178", "text": "Cleaning Supplies & Equipment", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Safety-Supplies/cat_SC1718", "text": "Safety Supplies", "level": 1}
{"url": "http://www.staples.com/Personal-Protective-Equipment/cat_CG1398", "text": "Personal Protective Equipment (PPE)", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Trimmers-Punches-Scissors/cat_CG1249", "text": "Trimmers / Punches / Scissors", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Clipboards/cat_CL140606", "text": "Clipboards", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Paper-Towels-Tissues-Napkins/cat_DP1865", "text": "Paper Towels / Tissues / Napkins", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Post-it-Stickies-Notes-Flags/cat_DP4736", "text": "Post-it\u00ae / Stickies\u2122 Notes & Flags", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Custom-Business-Cards-Appointment-Cards-Accessories/cat_DP4975", "text": "Custom Business Cards, Appointment Cards & Accessories", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Accounting-Forms/cat_CG1283", "text": "Accounting / Forms", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Waste-Recycling/cat_CG2827", "text": "Waste / Recycling", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Vacuums-Mops-Floor-Care/cat_CG2826", "text": "Floorcare: Mops / Brooms / Vacuums", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Safety-Supplies/cat_CG1243", "text": "Safety Supplies", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Fire-Gas-Water-Protection/cat_DP5201", "text": "Fire, Gas & Water Protection", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Material-Handling/cat_CG1365", "text": "Material Handling", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Presentation-Folders/cat_CG1397", "text": "Custom Presentation Folders", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/File-Folder-Labels/cat_DP1518", "text": "File Folder Labels", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.comwww.staples.com/Staples-Manila-File-Folders-Letter-3-Tab-Assorted-Position-100-Box/product_116657", "text": "file folders", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.comhttp://www.staples.com/Hanging-File-Folders/cat_CL140599", "text": "hanging file folders", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Rulers-Measuring-Devices/cat_CL10503", "text": "Rulers & Measuring Devices", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Candy-Gum-Mint/cat_DP4695", "text": "Candy / Gum / Mint", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Edible-Gifts-Desserts/cat_CG1252", "text": "Edible Gifts / Desserts", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Index-Card-Index-Card-Storage/cat_DP2227", "text": "Index Card / Index Card Storage", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Name-Badges-Holders/cat_DP1520", "text": "ID Badges & Holders", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Stationery-Invitations/cat_DP1422", "text": "Stationery / Invitations", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.comhttp://www.staples.com/Poppin-Office-Supplies/cat_CG2907", "text": "Poppin Office Supplies", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Tools-Flashlights-Cords/cat_CG1244", "text": "Tools / Flashlights / Cords", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Safety-Signs/cat_CL167011", "text": "Safety Signs", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Traffic-Safety/cat_DP5085", "text": "Traffic Safety", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.comhttp://www.staples.com/View-Binders/cat_CL167205", "text": "binders", "level": 0, "parent_text": "Filing | Binders | Organizers", "parent_url": "http://www.staples.com/Filing-Binders-Organizers/cat_SC1677"}
{"url": "http://www.staples.com/Desk-Accessories-Rolodex/cat_CG22", "text": "Desk Accessories / Rolodex", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Calculators/cat_DP900", "text": "Calculators", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Clips-Tacks-Rubber-Bands/cat_CG1036", "text": "Clips / Tacks / Rubber Bands", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Stamps-Stamp-Pads/cat_DP2028", "text": "Stamps / Stamp Pads", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.comhttp://www.staples.com/Scientific-Calculators/cat_CL90002", "text": "scientific calculator", "level": 0, "parent_text": "Pens | Tape | Desk Supplies", "parent_url": "http://www.staples.com/Pens-Tape-Desk-Supplies/cat_SC1678"}
{"url": "http://www.staples.com/Snacks/cat_DP3722", "text": "Snacks", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Plates-Cups-Cutlery/cat_DP1621", "text": "Plates / Cups / Cutlery", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.comhttp://www.staples.com/Office-Supplies/cat_SC1", "text": "office supplies", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.comhttp://www.staples.com/Copy-Printer-Paper/cat_CG10", "text": "printer paper", "level": 0, "parent_text": "Paper | Notebooks | Post-its", "parent_url": "http://www.staples.com/Paper-Notebooks-Post-it/cat_SC1676"}
{"url": "http://www.staples.com/Heating-Cooling-Air-Quality/cat_DP4952", "text": "Heating / Cooling / Air Quality", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Kitchen-Appliances/cat_DP800", "text": "Kitchen Appliances", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Security-Early-Warning/cat_CG1388", "text": "Security & Early Warning", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Sorbents-Spill-Control/cat_CL165294", "text": "Sorbents & Spill Control", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Kitchen-Appliances/cat_DP800", "text": "Kitchen Appliances", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Catering-Food-Service/cat_CG1400", "text": "Catering/Food Service", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Batteries-Power/cat_CG75", "text": "Batteries & Power", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Candles/cat_CL166251", "text": "Candles", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Fall-Protection/cat_DP5079", "text": "Fall Protection", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Lubricants-Penetrants/cat_CG1373", "text": "Lubricants & Penetrants", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.comhttp://www.staples.com/Coffee-Makers/brandedcat_CL140860_Keurig_8132", "text": "Keurig coffee maker", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.comhttp://www.staples.com/K-Cups/cat_CL164886", "text": "Keurig K-Cups", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Light-Bulbs/cat_DP1476", "text": "Light Bulbs", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Paint-Paint-Supplies/cat_CG1374", "text": "Paint / Paint Supplies", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Personal-Care/cat_CG1313", "text": "Personal Care", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Adhesives-Sealants-Tapes/cat_CG1376", "text": "Adhesives, Sealants & Tapes", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Ice-Melt/cat_CL164825", "text": "Ice Melt", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Safety-Storage/cat_CG1364", "text": "Safety Storage", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.comhttp://www.staples.com/Folgers-Coffee-Coffee-Coffee-Makers-Sugar/brandedcat_CL141073_Folgers_7767", "text": "Folgers coffee", "level": 0, "parent_text": "Coffee | Water | Snacks", "parent_url": "http://www.staples.com/Coffee-Water-Snacks/cat_SC1684"}
{"url": "http://www.staples.com/Power-Strips-Cords-Plugs/cat_CG1375", "text": "Power Strips / Cords / Plugs", "level": 0, "parent_text": "Cleaning | Facilities | Tools", "parent_url": "http://www.staples.com/Cleaning-Facilities-Tools/cat_SC1683"}
{"url": "http://www.staples.com/Insect-Control/cat_CL165079", "text": "Insect Control", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/First-Aid-Wound-Care/cat_CG1424", "text": "First Aid / Wound Care", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Light-Bulbs/cat_DP1476", "text": "Light Bulbs", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Machine-Fluids/cat_DP5141", "text": "Machine Fluids", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929", "text": "First Aid | Medical Supplies", "level": 1}
{"url": "http://www.staples.com/First-Aid-Wound-Care/cat_CG1424", "text": "First Aid / Wound Care", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Medicine/cat_CG1442", "text": "Medicine", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Vitamins/cat_CG1443", "text": "Vitamins", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Power-Strips-Cords-Plugs/cat_CG1375", "text": "Power Strips / Cords / Plugs", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Wipers/cat_CL159267", "text": "Wipers", "level": 0, "parent_text": "Safety Supplies", "parent_url": "http://www.staples.com/Safety-Supplies/cat_SC1718"}
{"url": "http://www.staples.com/Feeding-Tubes-Nutrients/cat_CG1448", "text": "Feeding Tubes / Nutrients", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Apparel-Staff-Patient/cat_CG1430", "text": "Apparel: Staff / Patient", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Medical-Gloves/cat_CG1428", "text": "Medical Gloves", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Instruments-Diagnostic-Exam/cat_CG1445", "text": "Instruments: Diagnostic / Exam", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Surgical-Prep-Masks-Anesthesia/cat_CG1441", "text": "Surgical Prep / Masks / Anesthesia", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Nursing-Procedure-Supplies/cat_CG1434", "text": "Nursing Procedure Supplies", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Beds-Bedside-Care/cat_CG1435", "text": "Beds / Bedside Care", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Exam-Paper-Drapes/cat_CG1447", "text": "Exam Paper / Drapes", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Medical-Waste-Disposal/cat_CG1444", "text": "Medical Waste Disposal", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Wheelchairs-Canes-Walkers/cat_CG1436", "text": "Wheelchairs / Canes / Walkers", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Orthopedic-Supports-Living-Aids/cat_CG1432", "text": "Orthopedic / Supports / Living Aids", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Restraints-Lifts-Patient-Transfer/cat_CG1429", "text": "Restraints / Lifts / Patient Transfer", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Shower-Bath-Aids/cat_CG1426", "text": "Shower / Bath Aids", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Incontinence/cat_CG1431", "text": "Incontinence", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Personal-Bath-Care/cat_CG1433", "text": "Personal & Bath Care", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Maternity-Baby-Care/cat_CG1425", "text": "Maternity / Baby Care", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Patient-Admission-Supplies/cat_CG1439", "text": "Patient Admission Supplies", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Urology-Ostomy/cat_CG1446", "text": "Urology / Ostomy", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Respiratory/cat_CG1440", "text": "Respiratory", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
{"url": "http://www.staples.com/Medical-Furnishings-Machines/cat_DP4150", "text": "Medical Furnishings & Machines", "level": 0, "parent_text": "First Aid | Medical Supplies", "parent_url": "http://www.staples.com/First-Aid-Medical-Supplies/cat_SC1929"}
