<?php

/**
 *  @file ifilters.php
 *  @brief IFilters interface is used for uniting filters_values and filters_items app models
 *  @author Oleg Meleshko <qu1ze34@gmail.com>
 */

interface IFilters
{
	const ICON_BLUE = 'assess_report_seo.png';
	const ICON_YELLOW = 'assess_report_yellow.png';
	const ICON_RED = 'assess_report_seo_red.png';
	
	const ASSESS_REPORT_TOTAL_ITEMS = 1;
	const ASSESS_REPORT_TOTAL_ITEMS_COMPETITOR = 2;
	const ASSESS_REPORT_ITEMS_PRICED_HIGHER_THAN_COMPETITORS = 3;
	const SKUS_SHORTER_THAN_COMPETITOR_PRODUCT_CONTENT = 4;
	const SKUS_LONGER_THAN_COMPETITOR_PRODUCT_CONTENT = 5;
	const SKUS_SAME_COMPETITOR_PRODUCT_CONTENT = 6;
	const SKUS_FEWER_50_PRODUCT_CONTENT = 7;
	const SKUS_FEWER_50_PRODUCT_CONTENT_COMPETITOR = 8;
	const SKUS_FEWER_100_PRODUCT_CONTENT = 9;
	const SKUS_FEWER_100_PRODUCT_CONTENT_COMPETITOR = 10;
	const SKUS_FEWER_150_PRODUCT_CONTENT = 11;
	const SKUS_FEWER_150_PRODUCT_CONTENT_COMPETITOR = 12;
	const SKUS_FEWER_COMPETITOR_OPTIMIZED_KEYWORDS = 13;
	const SKUS_ZERO_OPTIMIZED_KEYWORDS = 14;
	const SKUS_ZERO_OPTIMIZED_KEYWORDS_COMPETITOR = 15;
	const SKUS_ONE_OPTIMIZED_KEYWORDS = 16;
	const SKUS_ONE_OPTIMIZED_KEYWORDS_COMPETITOR = 17;
	const SKUS_TWO_OPTIMIZED_KEYWORDS = 18;
	const SKUS_TWO_OPTIMIZED_KEYWORDS_COMPETITOR = 19;
	const SKUS_THREE_OPTIMIZED_KEYWORDS = 20;
	const SKUS_THREE_OPTIMIZED_KEYWORDS_COMPETITOR = 21;
	const SKUS_TITLE_LESS_THAN_70_CHARS = 22;
	const SKUS_TITLE_LESS_THAN_70_CHARS_COMPETITOR = 23;
	const SKUS_TITLE_MORE_THAN_70_CHARS = 24;
	const SKUS_TITLE_MORE_THAN_70_CHARS_COMPETITOR = 25;
	const SKUS_WITH_NO_PRODUCT_IMAGES = 26;
	const SKUS_WITH_NO_PRODUCT_IMAGES_COMPETITOR = 27;
	const SKUS_WITH_ONE_PRODUCT_IMAGE = 28;
	const SKUS_WITH_ONE_PRODUCT_IMAGE_COMPETITOR = 29;
	const SKUS_WITH_MORE_THAN_ONE_PRODUCT_IMAGE = 30;
	const SKUS_WITH_MORE_THAN_ONE_PRODUCT_IMAGE_COMPETITOR = 31;
	const SKUS_FEWER_REVIEWS_THAN_COMPETITOR = 32;
	const SKUS_ZERO_REVIEWS = 33;
	const SKUS_ZERO_REVIEWS_COMPETITOR = 34;
	const SKUS_ONE_FOUR_REVIEWS = 35;
	const SKUS_ONE_FOUR_REVIEWS_COMPETITOR = 36;
	const SKUS_MORE_THAN_FIVE_REVIEWS = 37;
	const SKUS_MORE_THAN_FIVE_REVIEWS_COMPETITOR = 38;
	const SKUS_MORE_THAN_HUNDRED_REVIEWS = 39;
	const SKUS_MORE_THAN_HUNDRED_REVIEWS_COMPETITOR = 40;
	const SKUS_FEWER_FEATURES_THAN_COMPETITOR = 41;
	const SKUS_FEATURES = 42;
	const SKUS_FEATURES_COMPETITOR = 43;
	const SKUS_75_DUPLICATE_CONTENT = 44;
	const SKUS_50_DUPLICATE_CONTENT = 45;
	const SKUS_25_DUPLICATE_CONTENT = 46;
	const SKUS_THIRD_PARTY_CONTENT = 47;
	const SKUS_THIRD_PARTY_CONTENT_COMPETITOR = 48;
	const SKUS_PDFS = 49;
	const SKUS_PDFS_COMPETITOR = 50;
	const SKUS_VIDEOS = 51;
	const SKUS_VIDEOS_COMPETITOR = 52;
	const SKUS_WITH_ZERO_PRODUCT_DESCRIPTION_LINKS = 53;
	const SKUS_WITH_ZERO_PRODUCT_DESCRIPTION_LINKS_COMPETITOR = 54;
	const SKUS_WITH_MORE_THAN_ONE_PRODUCT_DESCRIPTION_LINKS = 55;
	const SKUS_WITH_MORE_THAN_ONE_PRODUCT_DESCRIPTION_LINKS_COMPETITOR = 56;
	const SKUS_WITH_MANUFACTURER_VIDEOS = 57;
	const SKUS_WITH_MANUFACTURER_IMAGES = 58;
	const SKUS_WITH_MANUFACTURER_PAGES = 59;
	const ASSESS_REPORT_TOTAL_ITEMS_SELECTED_BY_FILTER = 60;
}