# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='APIUser',
        ),
    ]
