# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_address', models.CharField(max_length=32)),
                ('request_method', models.CharField(max_length=20)),
                ('request_path', models.CharField(max_length=400)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('run_time', models.FloatField()),
            ],
            options={
                'db_table': 'api_insights_log',
            },
        ),
    ]
